-- 스킬 미선택 행동 저장 스키마 마이그레이션 (SOMA-212)
-- 선행: battle-progress-schema.sql
-- 기존 테이블 변경: battle_actions.user_skill 을 nullable 로 완화한다.
-- 정책서 4.1 / 11절에 따라 제한 시간 안에 스킬을 선택하지 않은 행동은 선택 스킬이 없는 상태로 저장하고,
--   선택 후 발동 실패(user_skill 이 있고 user_skill_triggered 가 0)와 구분한다.
-- 컬럼 정의는 JPA 매핑이 MySQLDialect 로 생성하는 DDL 과 동일하다.
--   운영 프로파일의 ddl-auto 가 validate 이므로 타입이 어긋나면 기동이 실패한다.
-- information_schema 가드로 재실행해도 안전하다.

set @battle_action_user_skill_ddl := (
    select if(
        count(*) = 1,
        'alter table battle_actions
            modify column user_skill enum ('GROUND_ACORN_SHOT','GROUND_BARK_SHIELD','GROUND_BERRY_BITE','GROUND_BLOSSOM_HEAL','GROUND_CLOVER_LUCK','GROUND_EARTH_SHAKE','GROUND_FOREST_HIDE','GROUND_GARDEN_REST','GROUND_GRASS_ROLL','GROUND_GREEN_FLASH','GROUND_HARVEST_BOOST','GROUND_HILL_JUMP','GROUND_HONEY_TRAP','GROUND_LEAF_GUARD','GROUND_LEAF_SLASH','GROUND_LOG_ROLL','GROUND_MOSS_CUSHION','GROUND_MOUNTAIN_POSE','GROUND_MUD_DASH','GROUND_NATURE_CALL','GROUND_PAW_STRIKE','GROUND_POLLEN_SPARK','GROUND_ROOT_BIND','GROUND_SOIL_CHARGE','GROUND_SPROUT_STEP','GROUND_STONE_TAP','GROUND_SUNNY_NAP','GROUND_TAIL_SEED','GROUND_VINE_PULL','GROUND_WILD_SNIFF','SEA_AQUA_FLASH','SEA_AQUA_HEAL','SEA_BLUE_CURRENT','SEA_BUBBLE_GUARD','SEA_CORAL_HIDE','SEA_DEEP_BLUE','SEA_DOLPHIN_STEP','SEA_DRIFT_FLOAT','SEA_FOAM_ROLL','SEA_ICE_SPLASH','SEA_KELP_WRAP','SEA_LAGOON_REST','SEA_MARINE_CALL','SEA_MIST_BREATH','SEA_OCEAN_NAP','SEA_PEARL_SHOT','SEA_RAIN_DROP','SEA_REEF_JUMP','SEA_RIPPLE_STEP','SEA_SALT_SPARK','SEA_SEASHELL_SHIELD','SEA_SHELL_BITE','SEA_SPLASH_PAW','SEA_STREAM_CUT','SEA_TIDAL_BOOST','SEA_TIDE_PULL','SEA_TURTLE_GUARD','SEA_WATER_TAIL','SEA_WAVE_DASH','SEA_WHIRLPOOL','SKY_AERIAL_POUNCE','SKY_AIR_SPIN','SKY_BIRDSONG_CALL','SKY_BLUE_FLASH','SKY_BREEZE_HEAL','SKY_CLEAR_MIND','SKY_CLOUD_BURST','SKY_CLOUD_CUSHION','SKY_CLOUD_HIDE','SKY_CLOUD_JUMP','SKY_COTTON_SHIELD','SKY_FEATHER_GUARD','SKY_FLOATING_STEP','SKY_GUST_PUSH','SKY_HALO_GLOW','SKY_HIGH_NOSE','SKY_LIGHT_RAINDROP','SKY_LIGHT_WING','SKY_MIST_WRAP','SKY_RAINBOW_TAIL','SKY_SKYLINE_RUN','SKY_SKY_PAW','SKY_SOFT_LANDING','SKY_STAR_BALLOON','SKY_SUNBEAM','SKY_TAILWIND','SKY_TWINKLE_EYE','SKY_UPDRAFT','SKY_WIND_CHIME','SKY_WIND_DASH','SPACE_ALIEN_WINK','SPACE_ASTRO_SHIELD','SPACE_AURORA_WAVE','SPACE_BLACKHOLE_PULL','SPACE_COMET_DASH','SPACE_COSMIC_DUST','SPACE_COSMIC_PAW','SPACE_DIMENSION_SKIP','SPACE_ECLIPSE_POSE','SPACE_GALAXY_SPARK','SPACE_GRAVITY_HOLD','SPACE_LUNAR_NAP','SPACE_METEOR_TAIL','SPACE_MILKY_WAY','SPACE_MOONBEAM','SPACE_MOON_GUARD','SPACE_NEBULA_HIDE','SPACE_NOVA_FLASH','SPACE_ORBIT_STEP','SPACE_PLANET_BOUNCE','SPACE_PULSAR_BEAT','SPACE_ROCKET_JUMP','SPACE_SATELLITE_SCAN','SPACE_STARDUST_HEAL','SPACE_STAR_PUNCH','SPACE_STAR_RING','SPACE_STAR_SEED','SPACE_UNIVERSE_CALL','SPACE_VOID_STEP','SPACE_ZERO_GRAVITY') null',
        'select 1')
    from information_schema.columns
    where table_schema = database()
      and table_name = 'battle_actions'
      and column_name = 'user_skill'
      and is_nullable = 'NO');
prepare battle_action_user_skill_stmt from @battle_action_user_skill_ddl;
execute battle_action_user_skill_stmt;
deallocate prepare battle_action_user_skill_stmt;
