-- 대전 코어 스키마 마이그레이션 (SOMA-208)
-- 신규 테이블: gym_leaders, gym_leader_animals, battles, battle_entries
-- 기존 테이블 변경: animals.rest_ends_at 컬럼 추가
-- 실행 순서: 이 스크립트 -> battle-progress-schema.sql -> gym-leader-thumbnail-schema.sql -> gym-leader-seed.sql
-- 컬럼 정의는 JPA 매핑이 MySQLDialect 로 생성하는 DDL 과 동일하다.
--   운영 프로파일의 ddl-auto 가 validate 이므로 타입이 어긋나면 기동이 실패한다.
--   CardSkill / CardType / Tier 상수를 추가하면 아래 enum 목록도 함께 갱신해야 한다.
-- create table if not exists / information_schema 가드로 재실행해도 안전하다.
-- FK 제약은 걸지 않는다. 이 저장소는 id 컬럼만 직접 보유하는 관례를 쓴다.

create table if not exists gym_leaders (
    challenge_order integer not null,
    created_at datetime(6) not null,
    deleted_at datetime(6),
    id bigint not null auto_increment,
    updated_at datetime(6) not null,
    name varchar(50) not null,
    badge_code varchar(64) not null,
    code varchar(64) not null,
    image_key varchar(255),
    primary key (id),
    unique key uk_gym_leaders_code (code),
    unique key uk_gym_leaders_challenge_order (challenge_order),
    unique key uk_gym_leaders_badge_code (badge_code)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;

create table if not exists gym_leader_animals (
    order_no integer not null,
    created_at datetime(6) not null,
    deleted_at datetime(6),
    gym_leader_id bigint not null,
    id bigint not null auto_increment,
    updated_at datetime(6) not null,
    animal_name varchar(255) not null,
    image_key varchar(255),
    card_type enum ('GROUND','SEA','SKY','SPACE') not null,
    skill_1 enum ('GROUND_ACORN_SHOT','GROUND_BARK_SHIELD','GROUND_BERRY_BITE','GROUND_BLOSSOM_HEAL','GROUND_CLOVER_LUCK','GROUND_EARTH_SHAKE','GROUND_FOREST_HIDE','GROUND_GARDEN_REST','GROUND_GRASS_ROLL','GROUND_GREEN_FLASH','GROUND_HARVEST_BOOST','GROUND_HILL_JUMP','GROUND_HONEY_TRAP','GROUND_LEAF_GUARD','GROUND_LEAF_SLASH','GROUND_LOG_ROLL','GROUND_MOSS_CUSHION','GROUND_MOUNTAIN_POSE','GROUND_MUD_DASH','GROUND_NATURE_CALL','GROUND_PAW_STRIKE','GROUND_POLLEN_SPARK','GROUND_ROOT_BIND','GROUND_SOIL_CHARGE','GROUND_SPROUT_STEP','GROUND_STONE_TAP','GROUND_SUNNY_NAP','GROUND_TAIL_SEED','GROUND_VINE_PULL','GROUND_WILD_SNIFF','SEA_AQUA_FLASH','SEA_AQUA_HEAL','SEA_BLUE_CURRENT','SEA_BUBBLE_GUARD','SEA_CORAL_HIDE','SEA_DEEP_BLUE','SEA_DOLPHIN_STEP','SEA_DRIFT_FLOAT','SEA_FOAM_ROLL','SEA_ICE_SPLASH','SEA_KELP_WRAP','SEA_LAGOON_REST','SEA_MARINE_CALL','SEA_MIST_BREATH','SEA_OCEAN_NAP','SEA_PEARL_SHOT','SEA_RAIN_DROP','SEA_REEF_JUMP','SEA_RIPPLE_STEP','SEA_SALT_SPARK','SEA_SEASHELL_SHIELD','SEA_SHELL_BITE','SEA_SPLASH_PAW','SEA_STREAM_CUT','SEA_TIDAL_BOOST','SEA_TIDE_PULL','SEA_TURTLE_GUARD','SEA_WATER_TAIL','SEA_WAVE_DASH','SEA_WHIRLPOOL','SKY_AERIAL_POUNCE','SKY_AIR_SPIN','SKY_BIRDSONG_CALL','SKY_BLUE_FLASH','SKY_BREEZE_HEAL','SKY_CLEAR_MIND','SKY_CLOUD_BURST','SKY_CLOUD_CUSHION','SKY_CLOUD_HIDE','SKY_CLOUD_JUMP','SKY_COTTON_SHIELD','SKY_FEATHER_GUARD','SKY_FLOATING_STEP','SKY_GUST_PUSH','SKY_HALO_GLOW','SKY_HIGH_NOSE','SKY_LIGHT_RAINDROP','SKY_LIGHT_WING','SKY_MIST_WRAP','SKY_RAINBOW_TAIL','SKY_SKYLINE_RUN','SKY_SKY_PAW','SKY_SOFT_LANDING','SKY_STAR_BALLOON','SKY_SUNBEAM','SKY_TAILWIND','SKY_TWINKLE_EYE','SKY_UPDRAFT','SKY_WIND_CHIME','SKY_WIND_DASH','SPACE_ALIEN_WINK','SPACE_ASTRO_SHIELD','SPACE_AURORA_WAVE','SPACE_BLACKHOLE_PULL','SPACE_COMET_DASH','SPACE_COSMIC_DUST','SPACE_COSMIC_PAW','SPACE_DIMENSION_SKIP','SPACE_ECLIPSE_POSE','SPACE_GALAXY_SPARK','SPACE_GRAVITY_HOLD','SPACE_LUNAR_NAP','SPACE_METEOR_TAIL','SPACE_MILKY_WAY','SPACE_MOONBEAM','SPACE_MOON_GUARD','SPACE_NEBULA_HIDE','SPACE_NOVA_FLASH','SPACE_ORBIT_STEP','SPACE_PLANET_BOUNCE','SPACE_PULSAR_BEAT','SPACE_ROCKET_JUMP','SPACE_SATELLITE_SCAN','SPACE_STARDUST_HEAL','SPACE_STAR_PUNCH','SPACE_STAR_RING','SPACE_STAR_SEED','SPACE_UNIVERSE_CALL','SPACE_VOID_STEP','SPACE_ZERO_GRAVITY') not null,
    skill_2 enum ('GROUND_ACORN_SHOT','GROUND_BARK_SHIELD','GROUND_BERRY_BITE','GROUND_BLOSSOM_HEAL','GROUND_CLOVER_LUCK','GROUND_EARTH_SHAKE','GROUND_FOREST_HIDE','GROUND_GARDEN_REST','GROUND_GRASS_ROLL','GROUND_GREEN_FLASH','GROUND_HARVEST_BOOST','GROUND_HILL_JUMP','GROUND_HONEY_TRAP','GROUND_LEAF_GUARD','GROUND_LEAF_SLASH','GROUND_LOG_ROLL','GROUND_MOSS_CUSHION','GROUND_MOUNTAIN_POSE','GROUND_MUD_DASH','GROUND_NATURE_CALL','GROUND_PAW_STRIKE','GROUND_POLLEN_SPARK','GROUND_ROOT_BIND','GROUND_SOIL_CHARGE','GROUND_SPROUT_STEP','GROUND_STONE_TAP','GROUND_SUNNY_NAP','GROUND_TAIL_SEED','GROUND_VINE_PULL','GROUND_WILD_SNIFF','SEA_AQUA_FLASH','SEA_AQUA_HEAL','SEA_BLUE_CURRENT','SEA_BUBBLE_GUARD','SEA_CORAL_HIDE','SEA_DEEP_BLUE','SEA_DOLPHIN_STEP','SEA_DRIFT_FLOAT','SEA_FOAM_ROLL','SEA_ICE_SPLASH','SEA_KELP_WRAP','SEA_LAGOON_REST','SEA_MARINE_CALL','SEA_MIST_BREATH','SEA_OCEAN_NAP','SEA_PEARL_SHOT','SEA_RAIN_DROP','SEA_REEF_JUMP','SEA_RIPPLE_STEP','SEA_SALT_SPARK','SEA_SEASHELL_SHIELD','SEA_SHELL_BITE','SEA_SPLASH_PAW','SEA_STREAM_CUT','SEA_TIDAL_BOOST','SEA_TIDE_PULL','SEA_TURTLE_GUARD','SEA_WATER_TAIL','SEA_WAVE_DASH','SEA_WHIRLPOOL','SKY_AERIAL_POUNCE','SKY_AIR_SPIN','SKY_BIRDSONG_CALL','SKY_BLUE_FLASH','SKY_BREEZE_HEAL','SKY_CLEAR_MIND','SKY_CLOUD_BURST','SKY_CLOUD_CUSHION','SKY_CLOUD_HIDE','SKY_CLOUD_JUMP','SKY_COTTON_SHIELD','SKY_FEATHER_GUARD','SKY_FLOATING_STEP','SKY_GUST_PUSH','SKY_HALO_GLOW','SKY_HIGH_NOSE','SKY_LIGHT_RAINDROP','SKY_LIGHT_WING','SKY_MIST_WRAP','SKY_RAINBOW_TAIL','SKY_SKYLINE_RUN','SKY_SKY_PAW','SKY_SOFT_LANDING','SKY_STAR_BALLOON','SKY_SUNBEAM','SKY_TAILWIND','SKY_TWINKLE_EYE','SKY_UPDRAFT','SKY_WIND_CHIME','SKY_WIND_DASH','SPACE_ALIEN_WINK','SPACE_ASTRO_SHIELD','SPACE_AURORA_WAVE','SPACE_BLACKHOLE_PULL','SPACE_COMET_DASH','SPACE_COSMIC_DUST','SPACE_COSMIC_PAW','SPACE_DIMENSION_SKIP','SPACE_ECLIPSE_POSE','SPACE_GALAXY_SPARK','SPACE_GRAVITY_HOLD','SPACE_LUNAR_NAP','SPACE_METEOR_TAIL','SPACE_MILKY_WAY','SPACE_MOONBEAM','SPACE_MOON_GUARD','SPACE_NEBULA_HIDE','SPACE_NOVA_FLASH','SPACE_ORBIT_STEP','SPACE_PLANET_BOUNCE','SPACE_PULSAR_BEAT','SPACE_ROCKET_JUMP','SPACE_SATELLITE_SCAN','SPACE_STARDUST_HEAL','SPACE_STAR_PUNCH','SPACE_STAR_RING','SPACE_STAR_SEED','SPACE_UNIVERSE_CALL','SPACE_VOID_STEP','SPACE_ZERO_GRAVITY') not null,
    tier enum ('A','B','C','S','SS','SSS') not null,
    primary key (id),
    unique key uk_gym_leader_animals_gym_leader_id_order_no (gym_leader_id, order_no)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;

create table if not exists battles (
    created_at datetime(6) not null,
    deleted_at datetime(6),
    ended_at datetime(6),
    gym_leader_id bigint not null,
    id bigint not null auto_increment,
    started_at datetime(6) not null,
    updated_at datetime(6) not null,
    user_id bigint not null,
    result enum ('LOSE','WIN'),
    status enum ('ABANDONED','FINISHED','IN_PROGRESS') not null,
    primary key (id),
    key idx_battles_user_id_started_at (user_id, started_at desc)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;

create table if not exists battle_entries (
    order_no integer not null,
    battle_id bigint not null,
    capture_id bigint,
    created_at datetime(6) not null,
    deleted_at datetime(6),
    gym_leader_animal_id bigint,
    id bigint not null auto_increment,
    updated_at datetime(6) not null,
    animal_name varchar(255) not null,
    card_type enum ('GROUND','SEA','SKY','SPACE') not null,
    side enum ('NPC','USER') not null,
    skill_1 enum ('GROUND_ACORN_SHOT','GROUND_BARK_SHIELD','GROUND_BERRY_BITE','GROUND_BLOSSOM_HEAL','GROUND_CLOVER_LUCK','GROUND_EARTH_SHAKE','GROUND_FOREST_HIDE','GROUND_GARDEN_REST','GROUND_GRASS_ROLL','GROUND_GREEN_FLASH','GROUND_HARVEST_BOOST','GROUND_HILL_JUMP','GROUND_HONEY_TRAP','GROUND_LEAF_GUARD','GROUND_LEAF_SLASH','GROUND_LOG_ROLL','GROUND_MOSS_CUSHION','GROUND_MOUNTAIN_POSE','GROUND_MUD_DASH','GROUND_NATURE_CALL','GROUND_PAW_STRIKE','GROUND_POLLEN_SPARK','GROUND_ROOT_BIND','GROUND_SOIL_CHARGE','GROUND_SPROUT_STEP','GROUND_STONE_TAP','GROUND_SUNNY_NAP','GROUND_TAIL_SEED','GROUND_VINE_PULL','GROUND_WILD_SNIFF','SEA_AQUA_FLASH','SEA_AQUA_HEAL','SEA_BLUE_CURRENT','SEA_BUBBLE_GUARD','SEA_CORAL_HIDE','SEA_DEEP_BLUE','SEA_DOLPHIN_STEP','SEA_DRIFT_FLOAT','SEA_FOAM_ROLL','SEA_ICE_SPLASH','SEA_KELP_WRAP','SEA_LAGOON_REST','SEA_MARINE_CALL','SEA_MIST_BREATH','SEA_OCEAN_NAP','SEA_PEARL_SHOT','SEA_RAIN_DROP','SEA_REEF_JUMP','SEA_RIPPLE_STEP','SEA_SALT_SPARK','SEA_SEASHELL_SHIELD','SEA_SHELL_BITE','SEA_SPLASH_PAW','SEA_STREAM_CUT','SEA_TIDAL_BOOST','SEA_TIDE_PULL','SEA_TURTLE_GUARD','SEA_WATER_TAIL','SEA_WAVE_DASH','SEA_WHIRLPOOL','SKY_AERIAL_POUNCE','SKY_AIR_SPIN','SKY_BIRDSONG_CALL','SKY_BLUE_FLASH','SKY_BREEZE_HEAL','SKY_CLEAR_MIND','SKY_CLOUD_BURST','SKY_CLOUD_CUSHION','SKY_CLOUD_HIDE','SKY_CLOUD_JUMP','SKY_COTTON_SHIELD','SKY_FEATHER_GUARD','SKY_FLOATING_STEP','SKY_GUST_PUSH','SKY_HALO_GLOW','SKY_HIGH_NOSE','SKY_LIGHT_RAINDROP','SKY_LIGHT_WING','SKY_MIST_WRAP','SKY_RAINBOW_TAIL','SKY_SKYLINE_RUN','SKY_SKY_PAW','SKY_SOFT_LANDING','SKY_STAR_BALLOON','SKY_SUNBEAM','SKY_TAILWIND','SKY_TWINKLE_EYE','SKY_UPDRAFT','SKY_WIND_CHIME','SKY_WIND_DASH','SPACE_ALIEN_WINK','SPACE_ASTRO_SHIELD','SPACE_AURORA_WAVE','SPACE_BLACKHOLE_PULL','SPACE_COMET_DASH','SPACE_COSMIC_DUST','SPACE_COSMIC_PAW','SPACE_DIMENSION_SKIP','SPACE_ECLIPSE_POSE','SPACE_GALAXY_SPARK','SPACE_GRAVITY_HOLD','SPACE_LUNAR_NAP','SPACE_METEOR_TAIL','SPACE_MILKY_WAY','SPACE_MOONBEAM','SPACE_MOON_GUARD','SPACE_NEBULA_HIDE','SPACE_NOVA_FLASH','SPACE_ORBIT_STEP','SPACE_PLANET_BOUNCE','SPACE_PULSAR_BEAT','SPACE_ROCKET_JUMP','SPACE_SATELLITE_SCAN','SPACE_STARDUST_HEAL','SPACE_STAR_PUNCH','SPACE_STAR_RING','SPACE_STAR_SEED','SPACE_UNIVERSE_CALL','SPACE_VOID_STEP','SPACE_ZERO_GRAVITY') not null,
    skill_2 enum ('GROUND_ACORN_SHOT','GROUND_BARK_SHIELD','GROUND_BERRY_BITE','GROUND_BLOSSOM_HEAL','GROUND_CLOVER_LUCK','GROUND_EARTH_SHAKE','GROUND_FOREST_HIDE','GROUND_GARDEN_REST','GROUND_GRASS_ROLL','GROUND_GREEN_FLASH','GROUND_HARVEST_BOOST','GROUND_HILL_JUMP','GROUND_HONEY_TRAP','GROUND_LEAF_GUARD','GROUND_LEAF_SLASH','GROUND_LOG_ROLL','GROUND_MOSS_CUSHION','GROUND_MOUNTAIN_POSE','GROUND_MUD_DASH','GROUND_NATURE_CALL','GROUND_PAW_STRIKE','GROUND_POLLEN_SPARK','GROUND_ROOT_BIND','GROUND_SOIL_CHARGE','GROUND_SPROUT_STEP','GROUND_STONE_TAP','GROUND_SUNNY_NAP','GROUND_TAIL_SEED','GROUND_VINE_PULL','GROUND_WILD_SNIFF','SEA_AQUA_FLASH','SEA_AQUA_HEAL','SEA_BLUE_CURRENT','SEA_BUBBLE_GUARD','SEA_CORAL_HIDE','SEA_DEEP_BLUE','SEA_DOLPHIN_STEP','SEA_DRIFT_FLOAT','SEA_FOAM_ROLL','SEA_ICE_SPLASH','SEA_KELP_WRAP','SEA_LAGOON_REST','SEA_MARINE_CALL','SEA_MIST_BREATH','SEA_OCEAN_NAP','SEA_PEARL_SHOT','SEA_RAIN_DROP','SEA_REEF_JUMP','SEA_RIPPLE_STEP','SEA_SALT_SPARK','SEA_SEASHELL_SHIELD','SEA_SHELL_BITE','SEA_SPLASH_PAW','SEA_STREAM_CUT','SEA_TIDAL_BOOST','SEA_TIDE_PULL','SEA_TURTLE_GUARD','SEA_WATER_TAIL','SEA_WAVE_DASH','SEA_WHIRLPOOL','SKY_AERIAL_POUNCE','SKY_AIR_SPIN','SKY_BIRDSONG_CALL','SKY_BLUE_FLASH','SKY_BREEZE_HEAL','SKY_CLEAR_MIND','SKY_CLOUD_BURST','SKY_CLOUD_CUSHION','SKY_CLOUD_HIDE','SKY_CLOUD_JUMP','SKY_COTTON_SHIELD','SKY_FEATHER_GUARD','SKY_FLOATING_STEP','SKY_GUST_PUSH','SKY_HALO_GLOW','SKY_HIGH_NOSE','SKY_LIGHT_RAINDROP','SKY_LIGHT_WING','SKY_MIST_WRAP','SKY_RAINBOW_TAIL','SKY_SKYLINE_RUN','SKY_SKY_PAW','SKY_SOFT_LANDING','SKY_STAR_BALLOON','SKY_SUNBEAM','SKY_TAILWIND','SKY_TWINKLE_EYE','SKY_UPDRAFT','SKY_WIND_CHIME','SKY_WIND_DASH','SPACE_ALIEN_WINK','SPACE_ASTRO_SHIELD','SPACE_AURORA_WAVE','SPACE_BLACKHOLE_PULL','SPACE_COMET_DASH','SPACE_COSMIC_DUST','SPACE_COSMIC_PAW','SPACE_DIMENSION_SKIP','SPACE_ECLIPSE_POSE','SPACE_GALAXY_SPARK','SPACE_GRAVITY_HOLD','SPACE_LUNAR_NAP','SPACE_METEOR_TAIL','SPACE_MILKY_WAY','SPACE_MOONBEAM','SPACE_MOON_GUARD','SPACE_NEBULA_HIDE','SPACE_NOVA_FLASH','SPACE_ORBIT_STEP','SPACE_PLANET_BOUNCE','SPACE_PULSAR_BEAT','SPACE_ROCKET_JUMP','SPACE_SATELLITE_SCAN','SPACE_STARDUST_HEAL','SPACE_STAR_PUNCH','SPACE_STAR_RING','SPACE_STAR_SEED','SPACE_UNIVERSE_CALL','SPACE_VOID_STEP','SPACE_ZERO_GRAVITY') not null,
    tier enum ('A','B','C','S','SS','SSS') not null,
    primary key (id),
    unique key uk_battle_entries_battle_id_side_order_no (battle_id, side, order_no),
    unique key uk_battle_entries_battle_id_capture_id (battle_id, capture_id)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;

-- animals.rest_ends_at (SOMA-202 2.5) - 출전 동물 휴식 종료 시각.
-- animals.capture_id 가 유니크라 animals 행 = 포착 개체 1:1 이고, captureId 기준 휴식과 동치다.
-- 선택도가 낮아 단독 인덱스는 만들지 않는다. 편성 후보 조회는 user_id 로 먼저 좁힌다.
set @battle_rest_ends_at_ddl := (
    select if(
        count(*) = 0,
        'alter table animals add column rest_ends_at datetime(6) null',
        'select 1')
    from information_schema.columns
    where table_schema = database()
      and table_name = 'animals'
      and column_name = 'rest_ends_at');
prepare battle_rest_ends_at_stmt from @battle_rest_ends_at_ddl;
execute battle_rest_ends_at_stmt;
deallocate prepare battle_rest_ends_at_stmt;
