CREATE TABLE `achievement_rewards` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL,
  `achievement_id` bigint NOT NULL,
  `amount` bigint DEFAULT NULL,
  `reference_code` varchar(64) DEFAULT NULL,
  `reward_type` enum('BADGE','COIN','EXPERIENCE') NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_achievement_rewards_achievement_id` (`achievement_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `achievements` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL,
  `category` enum('COLLECTION','EVENT','FARM') NOT NULL,
  `code` varchar(64) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `enabled` bit(1) NOT NULL,
  `metric` enum('MAX_OWNED_COUNT_PER_TYPE','ONLY_START_END_PLACED','OWNED_TYPE_COUNT','PLACED_ANIMAL_COUNT','PRE_REGISTRATION_CONVERTED') NOT NULL,
  `metric_param` varchar(32) DEFAULT NULL,
  `target_value` bigint NOT NULL,
  `title` varchar(100) NOT NULL,
  `achieved_image_key` varchar(255) DEFAULT NULL,
  `hidden` bit(1) NOT NULL,
  `unachieved_image_key` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_achievements_code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `animals` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL,
  `capture_id` bigint NOT NULL,
  `floor_num` int DEFAULT NULL,
  `slot_num` int DEFAULT NULL,
  `space_id` bigint DEFAULT NULL,
  `version` bigint NOT NULL,
  `rest_ends_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_animals_capture_id` (`capture_id`),
  KEY `idx_animals_space_id_floor_num_slot_num` (`space_id`,`floor_num`,`slot_num`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `anonymous_devices` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL,
  `ai_generated_at` datetime(6) DEFAULT NULL,
  `ai_generated_used` bit(1) DEFAULT NULL,
  `device_token` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_anonymous_devices_device_token` (`device_token`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `badges` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL,
  `code` varchar(64) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `image_key` varchar(255) DEFAULT NULL,
  `name` varchar(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_badges_code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `battle_actions` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL,
  `action_no_in_entry` int NOT NULL,
  `action_seq` int NOT NULL,
  `bar_position_after` int NOT NULL,
  `bar_position_before` int NOT NULL,
  `battle_id` bigint NOT NULL,
  `entry_order` int NOT NULL,
  `net_move_distance` int NOT NULL,
  `npc_move_distance` int NOT NULL,
  `npc_skill` enum('GROUND_ACORN_SHOT','GROUND_BARK_SHIELD','GROUND_BERRY_BITE','GROUND_BLOSSOM_HEAL','GROUND_CLOVER_LUCK','GROUND_EARTH_SHAKE','GROUND_FOREST_HIDE','GROUND_GARDEN_REST','GROUND_GRASS_ROLL','GROUND_GREEN_FLASH','GROUND_HARVEST_BOOST','GROUND_HILL_JUMP','GROUND_HONEY_TRAP','GROUND_LEAF_GUARD','GROUND_LEAF_SLASH','GROUND_LOG_ROLL','GROUND_MOSS_CUSHION','GROUND_MOUNTAIN_POSE','GROUND_MUD_DASH','GROUND_NATURE_CALL','GROUND_PAW_STRIKE','GROUND_POLLEN_SPARK','GROUND_ROOT_BIND','GROUND_SOIL_CHARGE','GROUND_SPROUT_STEP','GROUND_STONE_TAP','GROUND_SUNNY_NAP','GROUND_TAIL_SEED','GROUND_VINE_PULL','GROUND_WILD_SNIFF','SEA_AQUA_FLASH','SEA_AQUA_HEAL','SEA_BLUE_CURRENT','SEA_BUBBLE_GUARD','SEA_CORAL_HIDE','SEA_DEEP_BLUE','SEA_DOLPHIN_STEP','SEA_DRIFT_FLOAT','SEA_FOAM_ROLL','SEA_ICE_SPLASH','SEA_KELP_WRAP','SEA_LAGOON_REST','SEA_MARINE_CALL','SEA_MIST_BREATH','SEA_OCEAN_NAP','SEA_PEARL_SHOT','SEA_RAIN_DROP','SEA_REEF_JUMP','SEA_RIPPLE_STEP','SEA_SALT_SPARK','SEA_SEASHELL_SHIELD','SEA_SHELL_BITE','SEA_SPLASH_PAW','SEA_STREAM_CUT','SEA_TIDAL_BOOST','SEA_TIDE_PULL','SEA_TURTLE_GUARD','SEA_WATER_TAIL','SEA_WAVE_DASH','SEA_WHIRLPOOL','SKY_AERIAL_POUNCE','SKY_AIR_SPIN','SKY_BIRDSONG_CALL','SKY_BLUE_FLASH','SKY_BREEZE_HEAL','SKY_CLEAR_MIND','SKY_CLOUD_BURST','SKY_CLOUD_CUSHION','SKY_CLOUD_HIDE','SKY_CLOUD_JUMP','SKY_COTTON_SHIELD','SKY_FEATHER_GUARD','SKY_FLOATING_STEP','SKY_GUST_PUSH','SKY_HALO_GLOW','SKY_HIGH_NOSE','SKY_LIGHT_RAINDROP','SKY_LIGHT_WING','SKY_MIST_WRAP','SKY_RAINBOW_TAIL','SKY_SKYLINE_RUN','SKY_SKY_PAW','SKY_SOFT_LANDING','SKY_STAR_BALLOON','SKY_SUNBEAM','SKY_TAILWIND','SKY_TWINKLE_EYE','SKY_UPDRAFT','SKY_WIND_CHIME','SKY_WIND_DASH','SPACE_ALIEN_WINK','SPACE_ASTRO_SHIELD','SPACE_AURORA_WAVE','SPACE_BLACKHOLE_PULL','SPACE_COMET_DASH','SPACE_COSMIC_DUST','SPACE_COSMIC_PAW','SPACE_DIMENSION_SKIP','SPACE_ECLIPSE_POSE','SPACE_GALAXY_SPARK','SPACE_GRAVITY_HOLD','SPACE_LUNAR_NAP','SPACE_METEOR_TAIL','SPACE_MILKY_WAY','SPACE_MOONBEAM','SPACE_MOON_GUARD','SPACE_NEBULA_HIDE','SPACE_NOVA_FLASH','SPACE_ORBIT_STEP','SPACE_PLANET_BOUNCE','SPACE_PULSAR_BEAT','SPACE_ROCKET_JUMP','SPACE_SATELLITE_SCAN','SPACE_STARDUST_HEAL','SPACE_STAR_PUNCH','SPACE_STAR_RING','SPACE_STAR_SEED','SPACE_UNIVERSE_CALL','SPACE_VOID_STEP','SPACE_ZERO_GRAVITY') NOT NULL,
  `npc_skill_triggered` bit(1) NOT NULL,
  `user_move_distance` int NOT NULL,
  `user_skill` enum('GROUND_ACORN_SHOT','GROUND_BARK_SHIELD','GROUND_BERRY_BITE','GROUND_BLOSSOM_HEAL','GROUND_CLOVER_LUCK','GROUND_EARTH_SHAKE','GROUND_FOREST_HIDE','GROUND_GARDEN_REST','GROUND_GRASS_ROLL','GROUND_GREEN_FLASH','GROUND_HARVEST_BOOST','GROUND_HILL_JUMP','GROUND_HONEY_TRAP','GROUND_LEAF_GUARD','GROUND_LEAF_SLASH','GROUND_LOG_ROLL','GROUND_MOSS_CUSHION','GROUND_MOUNTAIN_POSE','GROUND_MUD_DASH','GROUND_NATURE_CALL','GROUND_PAW_STRIKE','GROUND_POLLEN_SPARK','GROUND_ROOT_BIND','GROUND_SOIL_CHARGE','GROUND_SPROUT_STEP','GROUND_STONE_TAP','GROUND_SUNNY_NAP','GROUND_TAIL_SEED','GROUND_VINE_PULL','GROUND_WILD_SNIFF','SEA_AQUA_FLASH','SEA_AQUA_HEAL','SEA_BLUE_CURRENT','SEA_BUBBLE_GUARD','SEA_CORAL_HIDE','SEA_DEEP_BLUE','SEA_DOLPHIN_STEP','SEA_DRIFT_FLOAT','SEA_FOAM_ROLL','SEA_ICE_SPLASH','SEA_KELP_WRAP','SEA_LAGOON_REST','SEA_MARINE_CALL','SEA_MIST_BREATH','SEA_OCEAN_NAP','SEA_PEARL_SHOT','SEA_RAIN_DROP','SEA_REEF_JUMP','SEA_RIPPLE_STEP','SEA_SALT_SPARK','SEA_SEASHELL_SHIELD','SEA_SHELL_BITE','SEA_SPLASH_PAW','SEA_STREAM_CUT','SEA_TIDAL_BOOST','SEA_TIDE_PULL','SEA_TURTLE_GUARD','SEA_WATER_TAIL','SEA_WAVE_DASH','SEA_WHIRLPOOL','SKY_AERIAL_POUNCE','SKY_AIR_SPIN','SKY_BIRDSONG_CALL','SKY_BLUE_FLASH','SKY_BREEZE_HEAL','SKY_CLEAR_MIND','SKY_CLOUD_BURST','SKY_CLOUD_CUSHION','SKY_CLOUD_HIDE','SKY_CLOUD_JUMP','SKY_COTTON_SHIELD','SKY_FEATHER_GUARD','SKY_FLOATING_STEP','SKY_GUST_PUSH','SKY_HALO_GLOW','SKY_HIGH_NOSE','SKY_LIGHT_RAINDROP','SKY_LIGHT_WING','SKY_MIST_WRAP','SKY_RAINBOW_TAIL','SKY_SKYLINE_RUN','SKY_SKY_PAW','SKY_SOFT_LANDING','SKY_STAR_BALLOON','SKY_SUNBEAM','SKY_TAILWIND','SKY_TWINKLE_EYE','SKY_UPDRAFT','SKY_WIND_CHIME','SKY_WIND_DASH','SPACE_ALIEN_WINK','SPACE_ASTRO_SHIELD','SPACE_AURORA_WAVE','SPACE_BLACKHOLE_PULL','SPACE_COMET_DASH','SPACE_COSMIC_DUST','SPACE_COSMIC_PAW','SPACE_DIMENSION_SKIP','SPACE_ECLIPSE_POSE','SPACE_GALAXY_SPARK','SPACE_GRAVITY_HOLD','SPACE_LUNAR_NAP','SPACE_METEOR_TAIL','SPACE_MILKY_WAY','SPACE_MOONBEAM','SPACE_MOON_GUARD','SPACE_NEBULA_HIDE','SPACE_NOVA_FLASH','SPACE_ORBIT_STEP','SPACE_PLANET_BOUNCE','SPACE_PULSAR_BEAT','SPACE_ROCKET_JUMP','SPACE_SATELLITE_SCAN','SPACE_STARDUST_HEAL','SPACE_STAR_PUNCH','SPACE_STAR_RING','SPACE_STAR_SEED','SPACE_UNIVERSE_CALL','SPACE_VOID_STEP','SPACE_ZERO_GRAVITY') DEFAULT NULL,
  `user_skill_triggered` bit(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_battle_actions_battle_id_action_seq` (`battle_id`,`action_seq`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `battle_broadcast_events` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL,
  `action_seq` int DEFAULT NULL,
  `battle_id` bigint NOT NULL,
  `entry_order` int DEFAULT NULL,
  `event_code` enum('BATTLE_POINT_APPLIED','SKILL_FAILED','SKILL_NOT_SELECTED','SKILL_OFFSET','SKILL_TRIGGERED','TIER_ADVANTAGE','TYPE_ADVANTAGE') NOT NULL,
  `event_seq` int NOT NULL,
  `param_animal_side` enum('NPC','USER') DEFAULT NULL,
  `param_skill` enum('GROUND_ACORN_SHOT','GROUND_BARK_SHIELD','GROUND_BERRY_BITE','GROUND_BLOSSOM_HEAL','GROUND_CLOVER_LUCK','GROUND_EARTH_SHAKE','GROUND_FOREST_HIDE','GROUND_GARDEN_REST','GROUND_GRASS_ROLL','GROUND_GREEN_FLASH','GROUND_HARVEST_BOOST','GROUND_HILL_JUMP','GROUND_HONEY_TRAP','GROUND_LEAF_GUARD','GROUND_LEAF_SLASH','GROUND_LOG_ROLL','GROUND_MOSS_CUSHION','GROUND_MOUNTAIN_POSE','GROUND_MUD_DASH','GROUND_NATURE_CALL','GROUND_PAW_STRIKE','GROUND_POLLEN_SPARK','GROUND_ROOT_BIND','GROUND_SOIL_CHARGE','GROUND_SPROUT_STEP','GROUND_STONE_TAP','GROUND_SUNNY_NAP','GROUND_TAIL_SEED','GROUND_VINE_PULL','GROUND_WILD_SNIFF','SEA_AQUA_FLASH','SEA_AQUA_HEAL','SEA_BLUE_CURRENT','SEA_BUBBLE_GUARD','SEA_CORAL_HIDE','SEA_DEEP_BLUE','SEA_DOLPHIN_STEP','SEA_DRIFT_FLOAT','SEA_FOAM_ROLL','SEA_ICE_SPLASH','SEA_KELP_WRAP','SEA_LAGOON_REST','SEA_MARINE_CALL','SEA_MIST_BREATH','SEA_OCEAN_NAP','SEA_PEARL_SHOT','SEA_RAIN_DROP','SEA_REEF_JUMP','SEA_RIPPLE_STEP','SEA_SALT_SPARK','SEA_SEASHELL_SHIELD','SEA_SHELL_BITE','SEA_SPLASH_PAW','SEA_STREAM_CUT','SEA_TIDAL_BOOST','SEA_TIDE_PULL','SEA_TURTLE_GUARD','SEA_WATER_TAIL','SEA_WAVE_DASH','SEA_WHIRLPOOL','SKY_AERIAL_POUNCE','SKY_AIR_SPIN','SKY_BIRDSONG_CALL','SKY_BLUE_FLASH','SKY_BREEZE_HEAL','SKY_CLEAR_MIND','SKY_CLOUD_BURST','SKY_CLOUD_CUSHION','SKY_CLOUD_HIDE','SKY_CLOUD_JUMP','SKY_COTTON_SHIELD','SKY_FEATHER_GUARD','SKY_FLOATING_STEP','SKY_GUST_PUSH','SKY_HALO_GLOW','SKY_HIGH_NOSE','SKY_LIGHT_RAINDROP','SKY_LIGHT_WING','SKY_MIST_WRAP','SKY_RAINBOW_TAIL','SKY_SKYLINE_RUN','SKY_SKY_PAW','SKY_SOFT_LANDING','SKY_STAR_BALLOON','SKY_SUNBEAM','SKY_TAILWIND','SKY_TWINKLE_EYE','SKY_UPDRAFT','SKY_WIND_CHIME','SKY_WIND_DASH','SPACE_ALIEN_WINK','SPACE_ASTRO_SHIELD','SPACE_AURORA_WAVE','SPACE_BLACKHOLE_PULL','SPACE_COMET_DASH','SPACE_COSMIC_DUST','SPACE_COSMIC_PAW','SPACE_DIMENSION_SKIP','SPACE_ECLIPSE_POSE','SPACE_GALAXY_SPARK','SPACE_GRAVITY_HOLD','SPACE_LUNAR_NAP','SPACE_METEOR_TAIL','SPACE_MILKY_WAY','SPACE_MOONBEAM','SPACE_MOON_GUARD','SPACE_NEBULA_HIDE','SPACE_NOVA_FLASH','SPACE_ORBIT_STEP','SPACE_PLANET_BOUNCE','SPACE_PULSAR_BEAT','SPACE_ROCKET_JUMP','SPACE_SATELLITE_SCAN','SPACE_STARDUST_HEAL','SPACE_STAR_PUNCH','SPACE_STAR_RING','SPACE_STAR_SEED','SPACE_UNIVERSE_CALL','SPACE_VOID_STEP','SPACE_ZERO_GRAVITY') DEFAULT NULL,
  `param_winner_side` enum('NPC','USER') DEFAULT NULL,
  `param_points` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_battle_broadcast_events_battle_id_event_seq` (`battle_id`,`event_seq`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `battle_entries` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL,
  `animal_name` varchar(255) NOT NULL,
  `battle_id` bigint NOT NULL,
  `capture_id` bigint DEFAULT NULL,
  `card_type` enum('GROUND','SEA','SKY','SPACE') NOT NULL,
  `gym_leader_animal_id` bigint DEFAULT NULL,
  `order_no` int NOT NULL,
  `side` enum('NPC','USER') NOT NULL,
  `skill_1` enum('GROUND_ACORN_SHOT','GROUND_BARK_SHIELD','GROUND_BERRY_BITE','GROUND_BLOSSOM_HEAL','GROUND_CLOVER_LUCK','GROUND_EARTH_SHAKE','GROUND_FOREST_HIDE','GROUND_GARDEN_REST','GROUND_GRASS_ROLL','GROUND_GREEN_FLASH','GROUND_HARVEST_BOOST','GROUND_HILL_JUMP','GROUND_HONEY_TRAP','GROUND_LEAF_GUARD','GROUND_LEAF_SLASH','GROUND_LOG_ROLL','GROUND_MOSS_CUSHION','GROUND_MOUNTAIN_POSE','GROUND_MUD_DASH','GROUND_NATURE_CALL','GROUND_PAW_STRIKE','GROUND_POLLEN_SPARK','GROUND_ROOT_BIND','GROUND_SOIL_CHARGE','GROUND_SPROUT_STEP','GROUND_STONE_TAP','GROUND_SUNNY_NAP','GROUND_TAIL_SEED','GROUND_VINE_PULL','GROUND_WILD_SNIFF','SEA_AQUA_FLASH','SEA_AQUA_HEAL','SEA_BLUE_CURRENT','SEA_BUBBLE_GUARD','SEA_CORAL_HIDE','SEA_DEEP_BLUE','SEA_DOLPHIN_STEP','SEA_DRIFT_FLOAT','SEA_FOAM_ROLL','SEA_ICE_SPLASH','SEA_KELP_WRAP','SEA_LAGOON_REST','SEA_MARINE_CALL','SEA_MIST_BREATH','SEA_OCEAN_NAP','SEA_PEARL_SHOT','SEA_RAIN_DROP','SEA_REEF_JUMP','SEA_RIPPLE_STEP','SEA_SALT_SPARK','SEA_SEASHELL_SHIELD','SEA_SHELL_BITE','SEA_SPLASH_PAW','SEA_STREAM_CUT','SEA_TIDAL_BOOST','SEA_TIDE_PULL','SEA_TURTLE_GUARD','SEA_WATER_TAIL','SEA_WAVE_DASH','SEA_WHIRLPOOL','SKY_AERIAL_POUNCE','SKY_AIR_SPIN','SKY_BIRDSONG_CALL','SKY_BLUE_FLASH','SKY_BREEZE_HEAL','SKY_CLEAR_MIND','SKY_CLOUD_BURST','SKY_CLOUD_CUSHION','SKY_CLOUD_HIDE','SKY_CLOUD_JUMP','SKY_COTTON_SHIELD','SKY_FEATHER_GUARD','SKY_FLOATING_STEP','SKY_GUST_PUSH','SKY_HALO_GLOW','SKY_HIGH_NOSE','SKY_LIGHT_RAINDROP','SKY_LIGHT_WING','SKY_MIST_WRAP','SKY_RAINBOW_TAIL','SKY_SKYLINE_RUN','SKY_SKY_PAW','SKY_SOFT_LANDING','SKY_STAR_BALLOON','SKY_SUNBEAM','SKY_TAILWIND','SKY_TWINKLE_EYE','SKY_UPDRAFT','SKY_WIND_CHIME','SKY_WIND_DASH','SPACE_ALIEN_WINK','SPACE_ASTRO_SHIELD','SPACE_AURORA_WAVE','SPACE_BLACKHOLE_PULL','SPACE_COMET_DASH','SPACE_COSMIC_DUST','SPACE_COSMIC_PAW','SPACE_DIMENSION_SKIP','SPACE_ECLIPSE_POSE','SPACE_GALAXY_SPARK','SPACE_GRAVITY_HOLD','SPACE_LUNAR_NAP','SPACE_METEOR_TAIL','SPACE_MILKY_WAY','SPACE_MOONBEAM','SPACE_MOON_GUARD','SPACE_NEBULA_HIDE','SPACE_NOVA_FLASH','SPACE_ORBIT_STEP','SPACE_PLANET_BOUNCE','SPACE_PULSAR_BEAT','SPACE_ROCKET_JUMP','SPACE_SATELLITE_SCAN','SPACE_STARDUST_HEAL','SPACE_STAR_PUNCH','SPACE_STAR_RING','SPACE_STAR_SEED','SPACE_UNIVERSE_CALL','SPACE_VOID_STEP','SPACE_ZERO_GRAVITY') NOT NULL,
  `skill_2` enum('GROUND_ACORN_SHOT','GROUND_BARK_SHIELD','GROUND_BERRY_BITE','GROUND_BLOSSOM_HEAL','GROUND_CLOVER_LUCK','GROUND_EARTH_SHAKE','GROUND_FOREST_HIDE','GROUND_GARDEN_REST','GROUND_GRASS_ROLL','GROUND_GREEN_FLASH','GROUND_HARVEST_BOOST','GROUND_HILL_JUMP','GROUND_HONEY_TRAP','GROUND_LEAF_GUARD','GROUND_LEAF_SLASH','GROUND_LOG_ROLL','GROUND_MOSS_CUSHION','GROUND_MOUNTAIN_POSE','GROUND_MUD_DASH','GROUND_NATURE_CALL','GROUND_PAW_STRIKE','GROUND_POLLEN_SPARK','GROUND_ROOT_BIND','GROUND_SOIL_CHARGE','GROUND_SPROUT_STEP','GROUND_STONE_TAP','GROUND_SUNNY_NAP','GROUND_TAIL_SEED','GROUND_VINE_PULL','GROUND_WILD_SNIFF','SEA_AQUA_FLASH','SEA_AQUA_HEAL','SEA_BLUE_CURRENT','SEA_BUBBLE_GUARD','SEA_CORAL_HIDE','SEA_DEEP_BLUE','SEA_DOLPHIN_STEP','SEA_DRIFT_FLOAT','SEA_FOAM_ROLL','SEA_ICE_SPLASH','SEA_KELP_WRAP','SEA_LAGOON_REST','SEA_MARINE_CALL','SEA_MIST_BREATH','SEA_OCEAN_NAP','SEA_PEARL_SHOT','SEA_RAIN_DROP','SEA_REEF_JUMP','SEA_RIPPLE_STEP','SEA_SALT_SPARK','SEA_SEASHELL_SHIELD','SEA_SHELL_BITE','SEA_SPLASH_PAW','SEA_STREAM_CUT','SEA_TIDAL_BOOST','SEA_TIDE_PULL','SEA_TURTLE_GUARD','SEA_WATER_TAIL','SEA_WAVE_DASH','SEA_WHIRLPOOL','SKY_AERIAL_POUNCE','SKY_AIR_SPIN','SKY_BIRDSONG_CALL','SKY_BLUE_FLASH','SKY_BREEZE_HEAL','SKY_CLEAR_MIND','SKY_CLOUD_BURST','SKY_CLOUD_CUSHION','SKY_CLOUD_HIDE','SKY_CLOUD_JUMP','SKY_COTTON_SHIELD','SKY_FEATHER_GUARD','SKY_FLOATING_STEP','SKY_GUST_PUSH','SKY_HALO_GLOW','SKY_HIGH_NOSE','SKY_LIGHT_RAINDROP','SKY_LIGHT_WING','SKY_MIST_WRAP','SKY_RAINBOW_TAIL','SKY_SKYLINE_RUN','SKY_SKY_PAW','SKY_SOFT_LANDING','SKY_STAR_BALLOON','SKY_SUNBEAM','SKY_TAILWIND','SKY_TWINKLE_EYE','SKY_UPDRAFT','SKY_WIND_CHIME','SKY_WIND_DASH','SPACE_ALIEN_WINK','SPACE_ASTRO_SHIELD','SPACE_AURORA_WAVE','SPACE_BLACKHOLE_PULL','SPACE_COMET_DASH','SPACE_COSMIC_DUST','SPACE_COSMIC_PAW','SPACE_DIMENSION_SKIP','SPACE_ECLIPSE_POSE','SPACE_GALAXY_SPARK','SPACE_GRAVITY_HOLD','SPACE_LUNAR_NAP','SPACE_METEOR_TAIL','SPACE_MILKY_WAY','SPACE_MOONBEAM','SPACE_MOON_GUARD','SPACE_NEBULA_HIDE','SPACE_NOVA_FLASH','SPACE_ORBIT_STEP','SPACE_PLANET_BOUNCE','SPACE_PULSAR_BEAT','SPACE_ROCKET_JUMP','SPACE_SATELLITE_SCAN','SPACE_STARDUST_HEAL','SPACE_STAR_PUNCH','SPACE_STAR_RING','SPACE_STAR_SEED','SPACE_UNIVERSE_CALL','SPACE_VOID_STEP','SPACE_ZERO_GRAVITY') NOT NULL,
  `tier` enum('A','B','C','S','SS','SSS') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_battle_entries_battle_id_side_order_no` (`battle_id`,`side`,`order_no`),
  UNIQUE KEY `uk_battle_entries_battle_id_capture_id` (`battle_id`,`capture_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `battles` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL,
  `ended_at` datetime(6) DEFAULT NULL,
  `gym_leader_id` bigint NOT NULL,
  `result` enum('LOSE','WIN') DEFAULT NULL,
  `started_at` datetime(6) NOT NULL,
  `status` enum('ABANDONED','FINISHED','IN_PROGRESS') NOT NULL,
  `user_id` bigint NOT NULL,
  `bar_position` int NOT NULL,
  `client_request_id` varchar(36) NOT NULL,
  `final_expires_at` datetime(6) DEFAULT NULL,
  `final_move_distance` int DEFAULT NULL,
  `final_tap_count` int DEFAULT NULL,
  `last_action_at` datetime(6) DEFAULT NULL,
  `final_points` int DEFAULT NULL,
  `final_ready_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_battles_user_id_client_request_id` (`user_id`,`client_request_id`),
  KEY `idx_battles_user_id_started_at` (`user_id`,`started_at` DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `capture_attempt_purchases` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL,
  `client_request_id` varchar(36) NOT NULL,
  `user_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_capture_attempt_purchases_user_request` (`user_id`,`client_request_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `captures` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL,
  `animal_image` varchar(255) DEFAULT NULL,
  `animal_name` varchar(255) NOT NULL,
  `card_image` varchar(255) DEFAULT NULL,
  `card_no` varchar(255) NOT NULL,
  `card_type` enum('GROUND','SEA','SKY','SPACE') NOT NULL,
  `client_request_id` varchar(36) NOT NULL,
  `elapsed_ms` int DEFAULT NULL,
  `failure_reason` varchar(255) DEFAULT NULL,
  `game_result_expires_at` datetime(6) NOT NULL,
  `game_status` enum('EXPIRED','FAILED','PENDING','SUCCEEDED') NOT NULL,
  `generation_status` enum('FAILED','PROCESSING','SUCCEEDED','WAITING_UPLOAD') NOT NULL,
  `granted_experience` bigint DEFAULT NULL,
  `original_image_content_type` varchar(255) NOT NULL,
  `original_image_key` varchar(255) NOT NULL,
  `skill_1` enum('GROUND_ACORN_SHOT','GROUND_BARK_SHIELD','GROUND_BERRY_BITE','GROUND_BLOSSOM_HEAL','GROUND_CLOVER_LUCK','GROUND_EARTH_SHAKE','GROUND_FOREST_HIDE','GROUND_GARDEN_REST','GROUND_GRASS_ROLL','GROUND_GREEN_FLASH','GROUND_HARVEST_BOOST','GROUND_HILL_JUMP','GROUND_HONEY_TRAP','GROUND_LEAF_GUARD','GROUND_LEAF_SLASH','GROUND_LOG_ROLL','GROUND_MOSS_CUSHION','GROUND_MOUNTAIN_POSE','GROUND_MUD_DASH','GROUND_NATURE_CALL','GROUND_PAW_STRIKE','GROUND_POLLEN_SPARK','GROUND_ROOT_BIND','GROUND_SOIL_CHARGE','GROUND_SPROUT_STEP','GROUND_STONE_TAP','GROUND_SUNNY_NAP','GROUND_TAIL_SEED','GROUND_VINE_PULL','GROUND_WILD_SNIFF','SEA_AQUA_FLASH','SEA_AQUA_HEAL','SEA_BLUE_CURRENT','SEA_BUBBLE_GUARD','SEA_CORAL_HIDE','SEA_DEEP_BLUE','SEA_DOLPHIN_STEP','SEA_DRIFT_FLOAT','SEA_FOAM_ROLL','SEA_ICE_SPLASH','SEA_KELP_WRAP','SEA_LAGOON_REST','SEA_MARINE_CALL','SEA_MIST_BREATH','SEA_OCEAN_NAP','SEA_PEARL_SHOT','SEA_RAIN_DROP','SEA_REEF_JUMP','SEA_RIPPLE_STEP','SEA_SALT_SPARK','SEA_SEASHELL_SHIELD','SEA_SHELL_BITE','SEA_SPLASH_PAW','SEA_STREAM_CUT','SEA_TIDAL_BOOST','SEA_TIDE_PULL','SEA_TURTLE_GUARD','SEA_WATER_TAIL','SEA_WAVE_DASH','SEA_WHIRLPOOL','SKY_AERIAL_POUNCE','SKY_AIR_SPIN','SKY_BIRDSONG_CALL','SKY_BLUE_FLASH','SKY_BREEZE_HEAL','SKY_CLEAR_MIND','SKY_CLOUD_BURST','SKY_CLOUD_CUSHION','SKY_CLOUD_HIDE','SKY_CLOUD_JUMP','SKY_COTTON_SHIELD','SKY_FEATHER_GUARD','SKY_FLOATING_STEP','SKY_GUST_PUSH','SKY_HALO_GLOW','SKY_HIGH_NOSE','SKY_LIGHT_RAINDROP','SKY_LIGHT_WING','SKY_MIST_WRAP','SKY_RAINBOW_TAIL','SKY_SKYLINE_RUN','SKY_SKY_PAW','SKY_SOFT_LANDING','SKY_STAR_BALLOON','SKY_SUNBEAM','SKY_TAILWIND','SKY_TWINKLE_EYE','SKY_UPDRAFT','SKY_WIND_CHIME','SKY_WIND_DASH','SPACE_ALIEN_WINK','SPACE_ASTRO_SHIELD','SPACE_AURORA_WAVE','SPACE_BLACKHOLE_PULL','SPACE_COMET_DASH','SPACE_COSMIC_DUST','SPACE_COSMIC_PAW','SPACE_DIMENSION_SKIP','SPACE_ECLIPSE_POSE','SPACE_GALAXY_SPARK','SPACE_GRAVITY_HOLD','SPACE_LUNAR_NAP','SPACE_METEOR_TAIL','SPACE_MILKY_WAY','SPACE_MOONBEAM','SPACE_MOON_GUARD','SPACE_NEBULA_HIDE','SPACE_NOVA_FLASH','SPACE_ORBIT_STEP','SPACE_PLANET_BOUNCE','SPACE_PULSAR_BEAT','SPACE_ROCKET_JUMP','SPACE_SATELLITE_SCAN','SPACE_STARDUST_HEAL','SPACE_STAR_PUNCH','SPACE_STAR_RING','SPACE_STAR_SEED','SPACE_UNIVERSE_CALL','SPACE_VOID_STEP','SPACE_ZERO_GRAVITY') NOT NULL,
  `skill_2` enum('GROUND_ACORN_SHOT','GROUND_BARK_SHIELD','GROUND_BERRY_BITE','GROUND_BLOSSOM_HEAL','GROUND_CLOVER_LUCK','GROUND_EARTH_SHAKE','GROUND_FOREST_HIDE','GROUND_GARDEN_REST','GROUND_GRASS_ROLL','GROUND_GREEN_FLASH','GROUND_HARVEST_BOOST','GROUND_HILL_JUMP','GROUND_HONEY_TRAP','GROUND_LEAF_GUARD','GROUND_LEAF_SLASH','GROUND_LOG_ROLL','GROUND_MOSS_CUSHION','GROUND_MOUNTAIN_POSE','GROUND_MUD_DASH','GROUND_NATURE_CALL','GROUND_PAW_STRIKE','GROUND_POLLEN_SPARK','GROUND_ROOT_BIND','GROUND_SOIL_CHARGE','GROUND_SPROUT_STEP','GROUND_STONE_TAP','GROUND_SUNNY_NAP','GROUND_TAIL_SEED','GROUND_VINE_PULL','GROUND_WILD_SNIFF','SEA_AQUA_FLASH','SEA_AQUA_HEAL','SEA_BLUE_CURRENT','SEA_BUBBLE_GUARD','SEA_CORAL_HIDE','SEA_DEEP_BLUE','SEA_DOLPHIN_STEP','SEA_DRIFT_FLOAT','SEA_FOAM_ROLL','SEA_ICE_SPLASH','SEA_KELP_WRAP','SEA_LAGOON_REST','SEA_MARINE_CALL','SEA_MIST_BREATH','SEA_OCEAN_NAP','SEA_PEARL_SHOT','SEA_RAIN_DROP','SEA_REEF_JUMP','SEA_RIPPLE_STEP','SEA_SALT_SPARK','SEA_SEASHELL_SHIELD','SEA_SHELL_BITE','SEA_SPLASH_PAW','SEA_STREAM_CUT','SEA_TIDAL_BOOST','SEA_TIDE_PULL','SEA_TURTLE_GUARD','SEA_WATER_TAIL','SEA_WAVE_DASH','SEA_WHIRLPOOL','SKY_AERIAL_POUNCE','SKY_AIR_SPIN','SKY_BIRDSONG_CALL','SKY_BLUE_FLASH','SKY_BREEZE_HEAL','SKY_CLEAR_MIND','SKY_CLOUD_BURST','SKY_CLOUD_CUSHION','SKY_CLOUD_HIDE','SKY_CLOUD_JUMP','SKY_COTTON_SHIELD','SKY_FEATHER_GUARD','SKY_FLOATING_STEP','SKY_GUST_PUSH','SKY_HALO_GLOW','SKY_HIGH_NOSE','SKY_LIGHT_RAINDROP','SKY_LIGHT_WING','SKY_MIST_WRAP','SKY_RAINBOW_TAIL','SKY_SKYLINE_RUN','SKY_SKY_PAW','SKY_SOFT_LANDING','SKY_STAR_BALLOON','SKY_SUNBEAM','SKY_TAILWIND','SKY_TWINKLE_EYE','SKY_UPDRAFT','SKY_WIND_CHIME','SKY_WIND_DASH','SPACE_ALIEN_WINK','SPACE_ASTRO_SHIELD','SPACE_AURORA_WAVE','SPACE_BLACKHOLE_PULL','SPACE_COMET_DASH','SPACE_COSMIC_DUST','SPACE_COSMIC_PAW','SPACE_DIMENSION_SKIP','SPACE_ECLIPSE_POSE','SPACE_GALAXY_SPARK','SPACE_GRAVITY_HOLD','SPACE_LUNAR_NAP','SPACE_METEOR_TAIL','SPACE_MILKY_WAY','SPACE_MOONBEAM','SPACE_MOON_GUARD','SPACE_NEBULA_HIDE','SPACE_NOVA_FLASH','SPACE_ORBIT_STEP','SPACE_PLANET_BOUNCE','SPACE_PULSAR_BEAT','SPACE_ROCKET_JUMP','SPACE_SATELLITE_SCAN','SPACE_STARDUST_HEAL','SPACE_STAR_PUNCH','SPACE_STAR_RING','SPACE_STAR_SEED','SPACE_UNIVERSE_CALL','SPACE_VOID_STEP','SPACE_ZERO_GRAVITY') NOT NULL,
  `tier` enum('A','B','C','S','SS','SSS') NOT NULL,
  `user_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_captures_user_id_client_request_id` (`user_id`,`client_request_id`),
  KEY `idx_captures_user_id_created_at` (`user_id`,`created_at`),
  KEY `idx_captures_user_id_card_type_animal_name` (`user_id`,`card_type`,`animal_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `characterizations` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL,
  `animal_name` varchar(255) NOT NULL,
  `card_no` varchar(255) DEFAULT NULL,
  `card_type` enum('GROUND','SEA','SKY','SPACE') DEFAULT NULL,
  `device_id` bigint NOT NULL,
  `elapsed_ms` int DEFAULT NULL,
  `failure_reason` varchar(255) DEFAULT NULL,
  `power` int DEFAULT NULL,
  `provider` varchar(255) DEFAULT NULL,
  `result_image_key` varchar(255) DEFAULT NULL,
  `animal_image_key` varchar(255) DEFAULT NULL,
  `skill_1` enum('GROUND_ACORN_SHOT','GROUND_BARK_SHIELD','GROUND_BERRY_BITE','GROUND_BLOSSOM_HEAL','GROUND_CLOVER_LUCK','GROUND_EARTH_SHAKE','GROUND_FOREST_HIDE','GROUND_GARDEN_REST','GROUND_GRASS_ROLL','GROUND_GREEN_FLASH','GROUND_HARVEST_BOOST','GROUND_HILL_JUMP','GROUND_HONEY_TRAP','GROUND_LEAF_GUARD','GROUND_LEAF_SLASH','GROUND_LOG_ROLL','GROUND_MOSS_CUSHION','GROUND_MOUNTAIN_POSE','GROUND_MUD_DASH','GROUND_NATURE_CALL','GROUND_PAW_STRIKE','GROUND_POLLEN_SPARK','GROUND_ROOT_BIND','GROUND_SOIL_CHARGE','GROUND_SPROUT_STEP','GROUND_STONE_TAP','GROUND_SUNNY_NAP','GROUND_TAIL_SEED','GROUND_VINE_PULL','GROUND_WILD_SNIFF','SEA_AQUA_FLASH','SEA_AQUA_HEAL','SEA_BLUE_CURRENT','SEA_BUBBLE_GUARD','SEA_CORAL_HIDE','SEA_DEEP_BLUE','SEA_DOLPHIN_STEP','SEA_DRIFT_FLOAT','SEA_FOAM_ROLL','SEA_ICE_SPLASH','SEA_KELP_WRAP','SEA_LAGOON_REST','SEA_MARINE_CALL','SEA_MIST_BREATH','SEA_OCEAN_NAP','SEA_PEARL_SHOT','SEA_RAIN_DROP','SEA_REEF_JUMP','SEA_RIPPLE_STEP','SEA_SALT_SPARK','SEA_SEASHELL_SHIELD','SEA_SHELL_BITE','SEA_SPLASH_PAW','SEA_STREAM_CUT','SEA_TIDAL_BOOST','SEA_TIDE_PULL','SEA_TURTLE_GUARD','SEA_WATER_TAIL','SEA_WAVE_DASH','SEA_WHIRLPOOL','SKY_AERIAL_POUNCE','SKY_AIR_SPIN','SKY_BIRDSONG_CALL','SKY_BLUE_FLASH','SKY_BREEZE_HEAL','SKY_CLEAR_MIND','SKY_CLOUD_BURST','SKY_CLOUD_CUSHION','SKY_CLOUD_HIDE','SKY_CLOUD_JUMP','SKY_COTTON_SHIELD','SKY_FEATHER_GUARD','SKY_FLOATING_STEP','SKY_GUST_PUSH','SKY_HALO_GLOW','SKY_HIGH_NOSE','SKY_LIGHT_RAINDROP','SKY_LIGHT_WING','SKY_MIST_WRAP','SKY_RAINBOW_TAIL','SKY_SKYLINE_RUN','SKY_SKY_PAW','SKY_SOFT_LANDING','SKY_STAR_BALLOON','SKY_SUNBEAM','SKY_TAILWIND','SKY_TWINKLE_EYE','SKY_UPDRAFT','SKY_WIND_CHIME','SKY_WIND_DASH','SPACE_ALIEN_WINK','SPACE_ASTRO_SHIELD','SPACE_AURORA_WAVE','SPACE_BLACKHOLE_PULL','SPACE_COMET_DASH','SPACE_COSMIC_DUST','SPACE_COSMIC_PAW','SPACE_DIMENSION_SKIP','SPACE_ECLIPSE_POSE','SPACE_GALAXY_SPARK','SPACE_GRAVITY_HOLD','SPACE_LUNAR_NAP','SPACE_METEOR_TAIL','SPACE_MILKY_WAY','SPACE_MOONBEAM','SPACE_MOON_GUARD','SPACE_NEBULA_HIDE','SPACE_NOVA_FLASH','SPACE_ORBIT_STEP','SPACE_PLANET_BOUNCE','SPACE_PULSAR_BEAT','SPACE_ROCKET_JUMP','SPACE_SATELLITE_SCAN','SPACE_STARDUST_HEAL','SPACE_STAR_PUNCH','SPACE_STAR_RING','SPACE_STAR_SEED','SPACE_UNIVERSE_CALL','SPACE_VOID_STEP','SPACE_ZERO_GRAVITY') DEFAULT NULL,
  `skill_2` enum('GROUND_ACORN_SHOT','GROUND_BARK_SHIELD','GROUND_BERRY_BITE','GROUND_BLOSSOM_HEAL','GROUND_CLOVER_LUCK','GROUND_EARTH_SHAKE','GROUND_FOREST_HIDE','GROUND_GARDEN_REST','GROUND_GRASS_ROLL','GROUND_GREEN_FLASH','GROUND_HARVEST_BOOST','GROUND_HILL_JUMP','GROUND_HONEY_TRAP','GROUND_LEAF_GUARD','GROUND_LEAF_SLASH','GROUND_LOG_ROLL','GROUND_MOSS_CUSHION','GROUND_MOUNTAIN_POSE','GROUND_MUD_DASH','GROUND_NATURE_CALL','GROUND_PAW_STRIKE','GROUND_POLLEN_SPARK','GROUND_ROOT_BIND','GROUND_SOIL_CHARGE','GROUND_SPROUT_STEP','GROUND_STONE_TAP','GROUND_SUNNY_NAP','GROUND_TAIL_SEED','GROUND_VINE_PULL','GROUND_WILD_SNIFF','SEA_AQUA_FLASH','SEA_AQUA_HEAL','SEA_BLUE_CURRENT','SEA_BUBBLE_GUARD','SEA_CORAL_HIDE','SEA_DEEP_BLUE','SEA_DOLPHIN_STEP','SEA_DRIFT_FLOAT','SEA_FOAM_ROLL','SEA_ICE_SPLASH','SEA_KELP_WRAP','SEA_LAGOON_REST','SEA_MARINE_CALL','SEA_MIST_BREATH','SEA_OCEAN_NAP','SEA_PEARL_SHOT','SEA_RAIN_DROP','SEA_REEF_JUMP','SEA_RIPPLE_STEP','SEA_SALT_SPARK','SEA_SEASHELL_SHIELD','SEA_SHELL_BITE','SEA_SPLASH_PAW','SEA_STREAM_CUT','SEA_TIDAL_BOOST','SEA_TIDE_PULL','SEA_TURTLE_GUARD','SEA_WATER_TAIL','SEA_WAVE_DASH','SEA_WHIRLPOOL','SKY_AERIAL_POUNCE','SKY_AIR_SPIN','SKY_BIRDSONG_CALL','SKY_BLUE_FLASH','SKY_BREEZE_HEAL','SKY_CLEAR_MIND','SKY_CLOUD_BURST','SKY_CLOUD_CUSHION','SKY_CLOUD_HIDE','SKY_CLOUD_JUMP','SKY_COTTON_SHIELD','SKY_FEATHER_GUARD','SKY_FLOATING_STEP','SKY_GUST_PUSH','SKY_HALO_GLOW','SKY_HIGH_NOSE','SKY_LIGHT_RAINDROP','SKY_LIGHT_WING','SKY_MIST_WRAP','SKY_RAINBOW_TAIL','SKY_SKYLINE_RUN','SKY_SKY_PAW','SKY_SOFT_LANDING','SKY_STAR_BALLOON','SKY_SUNBEAM','SKY_TAILWIND','SKY_TWINKLE_EYE','SKY_UPDRAFT','SKY_WIND_CHIME','SKY_WIND_DASH','SPACE_ALIEN_WINK','SPACE_ASTRO_SHIELD','SPACE_AURORA_WAVE','SPACE_BLACKHOLE_PULL','SPACE_COMET_DASH','SPACE_COSMIC_DUST','SPACE_COSMIC_PAW','SPACE_DIMENSION_SKIP','SPACE_ECLIPSE_POSE','SPACE_GALAXY_SPARK','SPACE_GRAVITY_HOLD','SPACE_LUNAR_NAP','SPACE_METEOR_TAIL','SPACE_MILKY_WAY','SPACE_MOONBEAM','SPACE_MOON_GUARD','SPACE_NEBULA_HIDE','SPACE_NOVA_FLASH','SPACE_ORBIT_STEP','SPACE_PLANET_BOUNCE','SPACE_PULSAR_BEAT','SPACE_ROCKET_JUMP','SPACE_SATELLITE_SCAN','SPACE_STARDUST_HEAL','SPACE_STAR_PUNCH','SPACE_STAR_RING','SPACE_STAR_SEED','SPACE_UNIVERSE_CALL','SPACE_VOID_STEP','SPACE_ZERO_GRAVITY') DEFAULT NULL,
  `status` enum('FAILED','PROCESSING','SUCCEEDED') NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_characterizations_status_created_at` (`status`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `coin_histories` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL,
  `amount` bigint NOT NULL,
  `balance_after` bigint NOT NULL,
  `reason` enum('FARM_FLOOR_PURCHASE','CAPTURE_ATTEMPT_PURCHASE','LEVEL_UP_REWARD','ACHIEVEMENT_REWARD','COUPON_COMPLETE_REWARD','GYM_LEADER_CLEAR_REWARD') NOT NULL,
  `reference_id` bigint DEFAULT NULL,
  `type` enum('EARN','SPEND') NOT NULL,
  `user_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_coin_histories_user_id_created_at` (`user_id`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `coupons` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL,
  `coupon_code` varchar(64) NOT NULL,
  `expires_at` datetime(6) NOT NULL,
  `status` enum('ACTIVE','EXPIRED','USED') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_coupons_coupon_code` (`coupon_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `daily_capture_attempts` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL,
  `attempt_date` date NOT NULL,
  `remaining` int NOT NULL,
  `user_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_daily_capture_attempts_user_date` (`user_id`,`attempt_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `farm_spaces` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL,
  `floor` int NOT NULL,
  `type` enum('GROUND','SEA','SKY','SPACE') NOT NULL,
  `user_id` bigint NOT NULL,
  `version` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_farm_spaces_user_id_type` (`user_id`,`type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `gym_leader_animals` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL,
  `animal_name` varchar(255) NOT NULL,
  `card_type` enum('GROUND','SEA','SKY','SPACE') NOT NULL,
  `gym_leader_id` bigint NOT NULL,
  `image_key` varchar(255) DEFAULT NULL,
  `order_no` int NOT NULL,
  `skill_1` enum('GROUND_ACORN_SHOT','GROUND_BARK_SHIELD','GROUND_BERRY_BITE','GROUND_BLOSSOM_HEAL','GROUND_CLOVER_LUCK','GROUND_EARTH_SHAKE','GROUND_FOREST_HIDE','GROUND_GARDEN_REST','GROUND_GRASS_ROLL','GROUND_GREEN_FLASH','GROUND_HARVEST_BOOST','GROUND_HILL_JUMP','GROUND_HONEY_TRAP','GROUND_LEAF_GUARD','GROUND_LEAF_SLASH','GROUND_LOG_ROLL','GROUND_MOSS_CUSHION','GROUND_MOUNTAIN_POSE','GROUND_MUD_DASH','GROUND_NATURE_CALL','GROUND_PAW_STRIKE','GROUND_POLLEN_SPARK','GROUND_ROOT_BIND','GROUND_SOIL_CHARGE','GROUND_SPROUT_STEP','GROUND_STONE_TAP','GROUND_SUNNY_NAP','GROUND_TAIL_SEED','GROUND_VINE_PULL','GROUND_WILD_SNIFF','SEA_AQUA_FLASH','SEA_AQUA_HEAL','SEA_BLUE_CURRENT','SEA_BUBBLE_GUARD','SEA_CORAL_HIDE','SEA_DEEP_BLUE','SEA_DOLPHIN_STEP','SEA_DRIFT_FLOAT','SEA_FOAM_ROLL','SEA_ICE_SPLASH','SEA_KELP_WRAP','SEA_LAGOON_REST','SEA_MARINE_CALL','SEA_MIST_BREATH','SEA_OCEAN_NAP','SEA_PEARL_SHOT','SEA_RAIN_DROP','SEA_REEF_JUMP','SEA_RIPPLE_STEP','SEA_SALT_SPARK','SEA_SEASHELL_SHIELD','SEA_SHELL_BITE','SEA_SPLASH_PAW','SEA_STREAM_CUT','SEA_TIDAL_BOOST','SEA_TIDE_PULL','SEA_TURTLE_GUARD','SEA_WATER_TAIL','SEA_WAVE_DASH','SEA_WHIRLPOOL','SKY_AERIAL_POUNCE','SKY_AIR_SPIN','SKY_BIRDSONG_CALL','SKY_BLUE_FLASH','SKY_BREEZE_HEAL','SKY_CLEAR_MIND','SKY_CLOUD_BURST','SKY_CLOUD_CUSHION','SKY_CLOUD_HIDE','SKY_CLOUD_JUMP','SKY_COTTON_SHIELD','SKY_FEATHER_GUARD','SKY_FLOATING_STEP','SKY_GUST_PUSH','SKY_HALO_GLOW','SKY_HIGH_NOSE','SKY_LIGHT_RAINDROP','SKY_LIGHT_WING','SKY_MIST_WRAP','SKY_RAINBOW_TAIL','SKY_SKYLINE_RUN','SKY_SKY_PAW','SKY_SOFT_LANDING','SKY_STAR_BALLOON','SKY_SUNBEAM','SKY_TAILWIND','SKY_TWINKLE_EYE','SKY_UPDRAFT','SKY_WIND_CHIME','SKY_WIND_DASH','SPACE_ALIEN_WINK','SPACE_ASTRO_SHIELD','SPACE_AURORA_WAVE','SPACE_BLACKHOLE_PULL','SPACE_COMET_DASH','SPACE_COSMIC_DUST','SPACE_COSMIC_PAW','SPACE_DIMENSION_SKIP','SPACE_ECLIPSE_POSE','SPACE_GALAXY_SPARK','SPACE_GRAVITY_HOLD','SPACE_LUNAR_NAP','SPACE_METEOR_TAIL','SPACE_MILKY_WAY','SPACE_MOONBEAM','SPACE_MOON_GUARD','SPACE_NEBULA_HIDE','SPACE_NOVA_FLASH','SPACE_ORBIT_STEP','SPACE_PLANET_BOUNCE','SPACE_PULSAR_BEAT','SPACE_ROCKET_JUMP','SPACE_SATELLITE_SCAN','SPACE_STARDUST_HEAL','SPACE_STAR_PUNCH','SPACE_STAR_RING','SPACE_STAR_SEED','SPACE_UNIVERSE_CALL','SPACE_VOID_STEP','SPACE_ZERO_GRAVITY') NOT NULL,
  `skill_2` enum('GROUND_ACORN_SHOT','GROUND_BARK_SHIELD','GROUND_BERRY_BITE','GROUND_BLOSSOM_HEAL','GROUND_CLOVER_LUCK','GROUND_EARTH_SHAKE','GROUND_FOREST_HIDE','GROUND_GARDEN_REST','GROUND_GRASS_ROLL','GROUND_GREEN_FLASH','GROUND_HARVEST_BOOST','GROUND_HILL_JUMP','GROUND_HONEY_TRAP','GROUND_LEAF_GUARD','GROUND_LEAF_SLASH','GROUND_LOG_ROLL','GROUND_MOSS_CUSHION','GROUND_MOUNTAIN_POSE','GROUND_MUD_DASH','GROUND_NATURE_CALL','GROUND_PAW_STRIKE','GROUND_POLLEN_SPARK','GROUND_ROOT_BIND','GROUND_SOIL_CHARGE','GROUND_SPROUT_STEP','GROUND_STONE_TAP','GROUND_SUNNY_NAP','GROUND_TAIL_SEED','GROUND_VINE_PULL','GROUND_WILD_SNIFF','SEA_AQUA_FLASH','SEA_AQUA_HEAL','SEA_BLUE_CURRENT','SEA_BUBBLE_GUARD','SEA_CORAL_HIDE','SEA_DEEP_BLUE','SEA_DOLPHIN_STEP','SEA_DRIFT_FLOAT','SEA_FOAM_ROLL','SEA_ICE_SPLASH','SEA_KELP_WRAP','SEA_LAGOON_REST','SEA_MARINE_CALL','SEA_MIST_BREATH','SEA_OCEAN_NAP','SEA_PEARL_SHOT','SEA_RAIN_DROP','SEA_REEF_JUMP','SEA_RIPPLE_STEP','SEA_SALT_SPARK','SEA_SEASHELL_SHIELD','SEA_SHELL_BITE','SEA_SPLASH_PAW','SEA_STREAM_CUT','SEA_TIDAL_BOOST','SEA_TIDE_PULL','SEA_TURTLE_GUARD','SEA_WATER_TAIL','SEA_WAVE_DASH','SEA_WHIRLPOOL','SKY_AERIAL_POUNCE','SKY_AIR_SPIN','SKY_BIRDSONG_CALL','SKY_BLUE_FLASH','SKY_BREEZE_HEAL','SKY_CLEAR_MIND','SKY_CLOUD_BURST','SKY_CLOUD_CUSHION','SKY_CLOUD_HIDE','SKY_CLOUD_JUMP','SKY_COTTON_SHIELD','SKY_FEATHER_GUARD','SKY_FLOATING_STEP','SKY_GUST_PUSH','SKY_HALO_GLOW','SKY_HIGH_NOSE','SKY_LIGHT_RAINDROP','SKY_LIGHT_WING','SKY_MIST_WRAP','SKY_RAINBOW_TAIL','SKY_SKYLINE_RUN','SKY_SKY_PAW','SKY_SOFT_LANDING','SKY_STAR_BALLOON','SKY_SUNBEAM','SKY_TAILWIND','SKY_TWINKLE_EYE','SKY_UPDRAFT','SKY_WIND_CHIME','SKY_WIND_DASH','SPACE_ALIEN_WINK','SPACE_ASTRO_SHIELD','SPACE_AURORA_WAVE','SPACE_BLACKHOLE_PULL','SPACE_COMET_DASH','SPACE_COSMIC_DUST','SPACE_COSMIC_PAW','SPACE_DIMENSION_SKIP','SPACE_ECLIPSE_POSE','SPACE_GALAXY_SPARK','SPACE_GRAVITY_HOLD','SPACE_LUNAR_NAP','SPACE_METEOR_TAIL','SPACE_MILKY_WAY','SPACE_MOONBEAM','SPACE_MOON_GUARD','SPACE_NEBULA_HIDE','SPACE_NOVA_FLASH','SPACE_ORBIT_STEP','SPACE_PLANET_BOUNCE','SPACE_PULSAR_BEAT','SPACE_ROCKET_JUMP','SPACE_SATELLITE_SCAN','SPACE_STARDUST_HEAL','SPACE_STAR_PUNCH','SPACE_STAR_RING','SPACE_STAR_SEED','SPACE_UNIVERSE_CALL','SPACE_VOID_STEP','SPACE_ZERO_GRAVITY') NOT NULL,
  `tier` enum('A','B','C','S','SS','SSS') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_gym_leader_animals_gym_leader_id_order_no` (`gym_leader_id`,`order_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `gym_leader_clears` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL,
  `badge_code` varchar(64) NOT NULL,
  `battle_id` bigint NOT NULL,
  `coins_after` bigint NOT NULL,
  `experience_after` bigint NOT NULL,
  `experience_reward` bigint NOT NULL,
  `gym_leader_coin_reward` bigint NOT NULL,
  `gym_leader_id` bigint NOT NULL,
  `level_after` int NOT NULL,
  `level_before` int NOT NULL,
  `level_up_coin_reward` bigint NOT NULL,
  `required_experience_for_next_level` bigint NOT NULL,
  `user_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_gym_leader_clears_user_leader` (`user_id`,`gym_leader_id`),
  UNIQUE KEY `uk_gym_leader_clears_battle_id` (`battle_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `gym_leaders` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL,
  `badge_code` varchar(64) NOT NULL,
  `challenge_order` int NOT NULL,
  `code` varchar(64) NOT NULL,
  `image_key` varchar(255) DEFAULT NULL,
  `name` varchar(50) NOT NULL,
  `thumbnail_key` varchar(255) DEFAULT NULL,
  `difficulty` varchar(255) DEFAULT NULL,
  `leader_description` varchar(255) DEFAULT NULL,
  `leader_type` enum('GROUND','SEA','SKY','SPACE','MIXED') DEFAULT NULL,
  `tip_description` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_gym_leaders_code` (`code`),
  UNIQUE KEY `uk_gym_leaders_challenge_order` (`challenge_order`),
  UNIQUE KEY `uk_gym_leaders_badge_code` (`badge_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `pre_registration_coupon_recipients` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL,
  `capture_id` bigint DEFAULT NULL,
  `converted_at` datetime(6) DEFAULT NULL,
  `coupon_id` bigint NOT NULL,
  `pre_registration_id` bigint NOT NULL,
  `user_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_pre_registration_coupon_recipients_coupon_id` (`coupon_id`),
  UNIQUE KEY `uk_pre_registration_coupon_recipients_pre_registration_id` (`pre_registration_id`),
  UNIQUE KEY `uk_pre_registration_coupon_recipients_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `pre_registrations` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL,
  `characterization_id` bigint NOT NULL,
  `phone_number_encrypted` varchar(512) NOT NULL,
  `phone_number_hash` varchar(128) NOT NULL,
  `required_consent` bit(1) NOT NULL,
  `status` enum('CANCELED','REGISTERED') NOT NULL,
  `message_sent_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_pre_registrations_phone_number_hash` (`phone_number_hash`),
  KEY `idx_pre_registrations_phone_number_hash` (`phone_number_hash`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `user_achievements` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL,
  `achievement_id` bigint NOT NULL,
  `reward_claimed_at` datetime(6) DEFAULT NULL,
  `user_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_achievements_user_achievement` (`user_id`,`achievement_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `user_badges` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL,
  `badge_id` bigint NOT NULL,
  `user_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_badges_user_badge` (`user_id`,`badge_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `users` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL,
  `coins` bigint NOT NULL,
  `email` varchar(255) DEFAULT NULL,
  `experience` bigint NOT NULL,
  `level` int NOT NULL,
  `nickname` varchar(255) DEFAULT NULL,
  `provider` enum('APPLE','KAKAO','NAVER') NOT NULL,
  `provider_id` varchar(255) NOT NULL,
  `marketing_agreed_at` datetime(6) DEFAULT NULL,
  `required_terms_agreed_at` datetime(6) DEFAULT NULL,
  `service_quality_agreed_at` datetime(6) DEFAULT NULL,
  `withdrawal_reason` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_users_provider_email` (`provider`,`email`),
  UNIQUE KEY `uk_users_nickname` (`nickname`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `badges` (`id`, `created_at`, `deleted_at`, `updated_at`, `code`, `description`, `image_key`, `name`) VALUES (6,'2026-08-04 05:35:02.971493',NULL,'2026-08-07 08:06:00.680015','BDG001','사전예약으로 포착팜에 합류했다','public/badge/927a2b84-0dff-4562-b62d-fc763c342ab4.png','1기 포착단');
INSERT INTO `badges` (`id`, `created_at`, `deleted_at`, `updated_at`, `code`, `description`, `image_key`, `name`) VALUES (7,'2026-08-04 05:35:02.971493',NULL,'2026-08-07 08:19:02.562939','BDG002','농장에 동물을 처음 배치했다','public/badge/5372ab90-aa8a-4f13-926f-6713843b0cc3.png','첫 보금자리');
INSERT INTO `badges` (`id`, `created_at`, `deleted_at`, `updated_at`, `code`, `description`, `image_key`, `name`) VALUES (8,'2026-08-04 05:35:02.971493',NULL,'2026-08-07 08:11:13.142473','BDG003','같은 타입의 동물을 10마리 이상 모았다','public/badge/757ac787-6484-4201-b20c-88ed29a9aae0.png','한 우물 포착');
INSERT INTO `badges` (`id`, `created_at`, `deleted_at`, `updated_at`, `code`, `description`, `image_key`, `name`) VALUES (9,'2026-08-04 05:35:02.971493',NULL,'2026-08-07 08:11:22.213630','BDG004','모든 타입의 동물을 모았다','public/badge/3c262a7b-72d6-4024-9303-5ca2e56e4943.png','골고루 수집가');
INSERT INTO `badges` (`id`, `created_at`, `deleted_at`, `updated_at`, `code`, `description`, `image_key`, `name`) VALUES (10,'2026-08-04 05:35:02.971493',NULL,'2026-08-07 19:55:45.864938','BDG005','시작과 끝을 완성했다','public/badge/26faef2b-7a9c-42b1-a106-24599899f2b2.png','시작과 끝');
INSERT INTO `badges` (`id`, `created_at`, `deleted_at`, `updated_at`, `code`, `description`, `image_key`, `name`) VALUES (11,'2026-08-27 07:04:54.862874',NULL,'2026-09-10 02:37:44.364065','BDG006','새싹 관장 두더를 이겼다','public/badge/ae266295-50f2-4e81-b1d2-5099e26ae179.png','새싹 뱃지');
INSERT INTO `badges` (`id`, `created_at`, `deleted_at`, `updated_at`, `code`, `description`, `image_key`, `name`) VALUES (12,'2026-08-27 07:04:54.862874',NULL,'2026-09-10 02:37:51.627784','BDG007','물결 관장 포미를 이겼다','public/badge/3b690a2d-5fd1-45f2-a7de-b5ce01f89239.png','물결 뱃지');
INSERT INTO `badges` (`id`, `created_at`, `deleted_at`, `updated_at`, `code`, `description`, `image_key`, `name`) VALUES (13,'2026-08-27 07:04:54.862874',NULL,'2026-09-10 02:37:57.530397','BDG008','바람 관장 휘루를 이겼다','public/badge/1954e11d-3d85-43ff-9d49-b3ae3eb4b7ab.png','바람 뱃지');
INSERT INTO `badges` (`id`, `created_at`, `deleted_at`, `updated_at`, `code`, `description`, `image_key`, `name`) VALUES (14,'2026-08-27 07:04:54.862874',NULL,'2026-09-10 02:38:04.289117','BDG009','별빛 관장 노바를 이겼다','public/badge/a6540d73-f204-41b4-9c83-0742b241b37d.png','별빛 뱃지');
INSERT INTO `badges` (`id`, `created_at`, `deleted_at`, `updated_at`, `code`, `description`, `image_key`, `name`) VALUES (15,'2026-08-27 07:04:54.862874',NULL,'2026-09-10 02:38:21.156265','BDG010','숲바람 관장 라온을 이겼다','public/badge/8ff3388a-585a-4713-ad01-5fe93e5a1420.png','숲바람 뱃지');
INSERT INTO `badges` (`id`, `created_at`, `deleted_at`, `updated_at`, `code`, `description`, `image_key`, `name`) VALUES (16,'2026-08-27 07:04:54.862874',NULL,'2026-09-10 02:38:30.391538','BDG011','밤바다 관장 미르하를 이겼다','public/badge/503934b6-9dc2-4171-aa07-209f75dacde0.png','밤바다 뱃지');
INSERT INTO `badges` (`id`, `created_at`, `deleted_at`, `updated_at`, `code`, `description`, `image_key`, `name`) VALUES (17,'2026-08-27 07:04:54.862874',NULL,'2026-09-10 02:38:38.340881','BDG012','순환 관장 하울을 이겼다','public/badge/0cca95b9-d9dc-4954-99e8-1538ac8d35db.png','순환 뱃지');
INSERT INTO `badges` (`id`, `created_at`, `deleted_at`, `updated_at`, `code`, `description`, `image_key`, `name`) VALUES (18,'2026-08-27 07:04:54.862874',NULL,'2026-09-10 02:38:46.041663','BDG013','챔피언 아스트라를 이겼다','public/badge/5911ae30-89a2-4a66-b2a1-9826b7ea0928.png','챔피언 뱃지');

INSERT INTO `achievements` (`id`, `created_at`, `deleted_at`, `updated_at`, `category`, `code`, `description`, `enabled`, `metric`, `metric_param`, `target_value`, `title`, `achieved_image_key`, `hidden`, `unachieved_image_key`) VALUES (1,'2026-08-04 05:35:03.075498',NULL,'2026-08-15 17:49:17.627688','EVENT','ACH001','사전예약 쿠폰을 사용해 포착팜에 합류한다',b'1','PRE_REGISTRATION_CONVERTED',NULL,1,'1기 포착단','public/achievement/87941044-fb70-4881-aa39-e47090889001.png',b'0','public/achievement/f85b2d77-3202-4535-b012-19dd3f90672c.png');
INSERT INTO `achievements` (`id`, `created_at`, `deleted_at`, `updated_at`, `category`, `code`, `description`, `enabled`, `metric`, `metric_param`, `target_value`, `title`, `achieved_image_key`, `hidden`, `unachieved_image_key`) VALUES (2,'2026-08-04 05:35:03.075498',NULL,'2026-08-15 17:49:23.498388','FARM','ACH002','농장에 동물을 처음 배치한다',b'1','PLACED_ANIMAL_COUNT',NULL,1,'첫 보금자리','public/achievement/6833758d-0d65-46ce-bb5a-a36bb6e53d2f.png',b'0','public/achievement/28b4548f-f280-4beb-9c2e-3084809db629.png');
INSERT INTO `achievements` (`id`, `created_at`, `deleted_at`, `updated_at`, `category`, `code`, `description`, `enabled`, `metric`, `metric_param`, `target_value`, `title`, `achieved_image_key`, `hidden`, `unachieved_image_key`) VALUES (3,'2026-08-04 05:35:03.075498',NULL,'2026-08-15 17:49:28.326231','COLLECTION','ACH003','같은 타입의 동물을 10마리 이상 보유한다',b'1','MAX_OWNED_COUNT_PER_TYPE',NULL,10,'한 우물 포착','public/achievement/1fd8dd71-1543-460a-aace-aa83449e3b89.png',b'0','public/achievement/66364b45-eae2-4040-94cd-72ab6082ee10.png');
INSERT INTO `achievements` (`id`, `created_at`, `deleted_at`, `updated_at`, `category`, `code`, `description`, `enabled`, `metric`, `metric_param`, `target_value`, `title`, `achieved_image_key`, `hidden`, `unachieved_image_key`) VALUES (4,'2026-08-04 05:35:03.075498',NULL,'2026-08-15 17:49:33.914482','COLLECTION','ACH004','모든 타입의 동물을 1마리 이상 보유한다',b'1','OWNED_TYPE_COUNT',NULL,4,'골고루 수집가','public/achievement/c7e936d8-cd98-45d2-9105-9616e8a4ccfd.png',b'0','public/achievement/0bef9f23-e87e-40e9-aa63-6df91f6bfd63.png');
INSERT INTO `achievements` (`id`, `created_at`, `deleted_at`, `updated_at`, `category`, `code`, `description`, `enabled`, `metric`, `metric_param`, `target_value`, `title`, `achieved_image_key`, `hidden`, `unachieved_image_key`) VALUES (5,'2026-08-04 05:35:03.075498',NULL,'2026-08-15 17:53:44.926973','FARM','ACH005','시작과 끝을 완성했다',b'1','ONLY_START_END_PLACED',NULL,1,'시작과 끝','public/achievement/3a22b083-7c34-44e4-96d0-652c154ef974.png',b'1','public/achievement/85849fb5-967d-442f-b220-9fa9240a1227.png');

INSERT INTO `achievement_rewards` (`id`, `created_at`, `deleted_at`, `updated_at`, `achievement_id`, `amount`, `reference_code`, `reward_type`) VALUES (1,'2026-08-04 05:35:03.161493',NULL,'2026-08-04 06:07:34.693542',1,1000,NULL,'COIN');
INSERT INTO `achievement_rewards` (`id`, `created_at`, `deleted_at`, `updated_at`, `achievement_id`, `amount`, `reference_code`, `reward_type`) VALUES (2,'2026-08-04 05:35:03.161493',NULL,'2026-08-04 05:35:03.161493',2,1000,NULL,'COIN');
INSERT INTO `achievement_rewards` (`id`, `created_at`, `deleted_at`, `updated_at`, `achievement_id`, `amount`, `reference_code`, `reward_type`) VALUES (3,'2026-08-04 05:35:03.161493',NULL,'2026-08-04 05:35:03.161493',3,1000,NULL,'COIN');
INSERT INTO `achievement_rewards` (`id`, `created_at`, `deleted_at`, `updated_at`, `achievement_id`, `amount`, `reference_code`, `reward_type`) VALUES (4,'2026-08-04 05:35:03.161493',NULL,'2026-08-04 05:35:03.161493',4,1000,NULL,'COIN');
INSERT INTO `achievement_rewards` (`id`, `created_at`, `deleted_at`, `updated_at`, `achievement_id`, `amount`, `reference_code`, `reward_type`) VALUES (5,'2026-08-04 05:35:03.161493',NULL,'2026-08-04 05:35:03.161493',5,1000,NULL,'COIN');
INSERT INTO `achievement_rewards` (`id`, `created_at`, `deleted_at`, `updated_at`, `achievement_id`, `amount`, `reference_code`, `reward_type`) VALUES (8,'2026-08-04 05:35:03.235992',NULL,'2026-08-04 05:35:03.235992',1,NULL,'BDG001','BADGE');
INSERT INTO `achievement_rewards` (`id`, `created_at`, `deleted_at`, `updated_at`, `achievement_id`, `amount`, `reference_code`, `reward_type`) VALUES (9,'2026-08-04 05:35:03.235992',NULL,'2026-08-04 05:35:03.235992',2,NULL,'BDG002','BADGE');
INSERT INTO `achievement_rewards` (`id`, `created_at`, `deleted_at`, `updated_at`, `achievement_id`, `amount`, `reference_code`, `reward_type`) VALUES (10,'2026-08-04 05:35:03.235992',NULL,'2026-08-04 05:35:03.235992',3,NULL,'BDG003','BADGE');
INSERT INTO `achievement_rewards` (`id`, `created_at`, `deleted_at`, `updated_at`, `achievement_id`, `amount`, `reference_code`, `reward_type`) VALUES (11,'2026-08-04 05:35:03.235992',NULL,'2026-08-04 05:35:03.235992',4,NULL,'BDG004','BADGE');
INSERT INTO `achievement_rewards` (`id`, `created_at`, `deleted_at`, `updated_at`, `achievement_id`, `amount`, `reference_code`, `reward_type`) VALUES (12,'2026-08-04 05:35:03.235992',NULL,'2026-08-04 05:35:03.235992',5,NULL,'BDG005','BADGE');

INSERT INTO `gym_leaders` (`id`, `created_at`, `deleted_at`, `updated_at`, `badge_code`, `challenge_order`, `code`, `image_key`, `name`, `thumbnail_key`, `difficulty`, `leader_description`, `leader_type`, `tip_description`) VALUES (9,'2026-08-29 04:53:56.049501',NULL,'2026-09-04 08:47:25.181445','BDG006',1,'GYM001','public/gym-leader/7402ad0a-fcc6-45d9-97ab-f7ffeebb5bac.png','두더','public/gym-leader-thumbnail/362a7837-5a23-490f-8c79-8da0e6bc459f.png','하','땅의 기초를 익히는 관장','GROUND','방어 후 빈틈을 노려보세요');
INSERT INTO `gym_leaders` (`id`, `created_at`, `deleted_at`, `updated_at`, `badge_code`, `challenge_order`, `code`, `image_key`, `name`, `thumbnail_key`, `difficulty`, `leader_description`, `leader_type`, `tip_description`) VALUES (10,'2026-08-29 04:53:56.049501',NULL,'2026-09-04 08:48:28.636465','BDG007',2,'GYM002','public/gym-leader/3d53f727-c880-4616-9a9e-1f08e8c2f2fa.png','포미','public/gym-leader-thumbnail/fb0f144e-e340-4849-8ea3-cb3e796c6ff4.png','하','바다의 흐름을 다루는 관장','SEA','빠른 공격으로 압박하세요');
INSERT INTO `gym_leaders` (`id`, `created_at`, `deleted_at`, `updated_at`, `badge_code`, `challenge_order`, `code`, `image_key`, `name`, `thumbnail_key`, `difficulty`, `leader_description`, `leader_type`, `tip_description`) VALUES (11,'2026-08-29 04:53:56.049501',NULL,'2026-09-04 09:19:53.858303','BDG008',3,'GYM003','public/gym-leader/6693a3d7-94da-4c10-8045-9f4432c1d90d.png','휘루','public/gym-leader-thumbnail/a71f9655-f993-40ef-b962-3f882dc662f4.png','중','균형 잡힌 전투의 관장','SKY','후반 강적에 대비하세요');
INSERT INTO `gym_leaders` (`id`, `created_at`, `deleted_at`, `updated_at`, `badge_code`, `challenge_order`, `code`, `image_key`, `name`, `thumbnail_key`, `difficulty`, `leader_description`, `leader_type`, `tip_description`) VALUES (12,'2026-08-29 04:53:56.049501',NULL,'2026-09-04 08:49:20.884876','BDG009',4,'GYM004','public/gym-leader/4eb034a6-2d0b-4eb3-a6cb-e988eb580cd7.png','노바','public/gym-leader-thumbnail/17d4f431-21d9-4ded-9e86-85d8d27aaf14.png','중','변칙적인 전투의 관장','SPACE','다양한 타입을 준비하세요');
INSERT INTO `gym_leaders` (`id`, `created_at`, `deleted_at`, `updated_at`, `badge_code`, `challenge_order`, `code`, `image_key`, `name`, `thumbnail_key`, `difficulty`, `leader_description`, `leader_type`, `tip_description`) VALUES (13,'2026-08-29 04:53:56.049501',NULL,'2026-09-04 08:50:18.440136','BDG010',5,'GYM005','public/gym-leader/c283753b-aa43-4e41-815e-2e7c3b63a684.png','라온','public/gym-leader-thumbnail/6acda20e-5924-4b58-8b5b-57a98a2389f5.png','상','강한 동물을 이끄는 관장','GROUND','상성을 활용해 공략하세요');
INSERT INTO `gym_leaders` (`id`, `created_at`, `deleted_at`, `updated_at`, `badge_code`, `challenge_order`, `code`, `image_key`, `name`, `thumbnail_key`, `difficulty`, `leader_description`, `leader_type`, `tip_description`) VALUES (14,'2026-08-29 04:53:56.049501',NULL,'2026-09-04 08:50:58.132659','BDG011',6,'GYM006','public/gym-leader/30eccb4a-63c2-4780-bb6b-c01ef7585f0b.png','미르하','public/gym-leader-thumbnail/38c2341e-278f-46ce-83f1-552b4597b189.png','상','빈틈을 노리는 강한 관장','SEA','기술 순서를 잘 살펴보세요');
INSERT INTO `gym_leaders` (`id`, `created_at`, `deleted_at`, `updated_at`, `badge_code`, `challenge_order`, `code`, `image_key`, `name`, `thumbnail_key`, `difficulty`, `leader_description`, `leader_type`, `tip_description`) VALUES (15,'2026-08-29 04:53:56.049501',NULL,'2026-09-04 09:01:05.721056','BDG012',7,'GYM007','public/gym-leader/06022476-12c3-4e2f-babf-a95aa00f77b6.png','하울','public/gym-leader-thumbnail/36e5e7a0-19c8-403c-9bae-21056bb4abbc.png','최상','최상위 동물을 다루는 관장','MIXED','여러 타입에 대비하세요');
INSERT INTO `gym_leaders` (`id`, `created_at`, `deleted_at`, `updated_at`, `badge_code`, `challenge_order`, `code`, `image_key`, `name`, `thumbnail_key`, `difficulty`, `leader_description`, `leader_type`, `tip_description`) VALUES (16,'2026-08-29 04:53:56.049501',NULL,'2026-09-04 09:00:46.543844','BDG013',8,'GYM008','public/gym-leader/69cb07b7-0407-47cb-9033-203efbc5606d.png','아스트라','public/gym-leader-thumbnail/c0796195-ae45-4ecb-8edc-266420d33824.png','최상','최강의 동물들을 이끄는 관장','MIXED','최정예 팀으로 도전하세요');

INSERT INTO `gym_leader_animals` (`id`, `created_at`, `deleted_at`, `updated_at`, `animal_name`, `card_type`, `gym_leader_id`, `image_key`, `order_no`, `skill_1`, `skill_2`, `tier`) VALUES (1,'2026-08-27 07:04:54.886915',NULL,'2026-08-30 18:43:52.134587','도톨','GROUND',9,'public/gym-leader-animal/797eccc2-853b-47b8-898a-82b0dcfb1ff6.png',1,'GROUND_LEAF_GUARD','GROUND_MOSS_CUSHION','C');
INSERT INTO `gym_leader_animals` (`id`, `created_at`, `deleted_at`, `updated_at`, `animal_name`, `card_type`, `gym_leader_id`, `image_key`, `order_no`, `skill_1`, `skill_2`, `tier`) VALUES (2,'2026-08-27 07:04:54.886915',NULL,'2026-08-30 18:43:28.024595','모리','GROUND',9,'public/gym-leader-animal/446c6a16-de32-4296-934b-295d9651b777.png',2,'GROUND_BARK_SHIELD','GROUND_GARDEN_REST','C');
INSERT INTO `gym_leader_animals` (`id`, `created_at`, `deleted_at`, `updated_at`, `animal_name`, `card_type`, `gym_leader_id`, `image_key`, `order_no`, `skill_1`, `skill_2`, `tier`) VALUES (3,'2026-08-27 07:04:54.886915',NULL,'2026-08-31 03:28:35.916970','바우','GROUND',9,'public/gym-leader-animal/1e98f30d-6077-4c29-814c-e3e1f18214d6.png',3,'GROUND_MOUNTAIN_POSE','GROUND_STONE_TAP','B');
INSERT INTO `gym_leader_animals` (`id`, `created_at`, `deleted_at`, `updated_at`, `animal_name`, `card_type`, `gym_leader_id`, `image_key`, `order_no`, `skill_1`, `skill_2`, `tier`) VALUES (4,'2026-08-27 07:04:54.886915',NULL,'2026-08-30 18:51:13.701972','파도리','SEA',10,'public/gym-leader-animal/b71747c7-c0c7-41a7-9ae5-eaac76809838.png',1,'SEA_BUBBLE_GUARD','SEA_CORAL_HIDE','C');
INSERT INTO `gym_leader_animals` (`id`, `created_at`, `deleted_at`, `updated_at`, `animal_name`, `card_type`, `gym_leader_id`, `image_key`, `order_no`, `skill_1`, `skill_2`, `tier`) VALUES (5,'2026-08-27 07:04:54.886915',NULL,'2026-08-30 18:51:18.532639','조개비','SEA',10,'public/gym-leader-animal/d8d0453b-76d3-4e81-8524-29a3297e485e.png',2,'SEA_SEASHELL_SHIELD','SEA_FOAM_ROLL','B');
INSERT INTO `gym_leader_animals` (`id`, `created_at`, `deleted_at`, `updated_at`, `animal_name`, `card_type`, `gym_leader_id`, `image_key`, `order_no`, `skill_1`, `skill_2`, `tier`) VALUES (6,'2026-08-27 07:04:54.886915',NULL,'2026-08-31 03:28:59.823965','미르','SEA',10,'public/gym-leader-animal/45addc7c-70f9-4d1f-b4e9-8c1b0b92e9c6.png',3,'SEA_TURTLE_GUARD','SEA_DOLPHIN_STEP','B');
INSERT INTO `gym_leader_animals` (`id`, `created_at`, `deleted_at`, `updated_at`, `animal_name`, `card_type`, `gym_leader_id`, `image_key`, `order_no`, `skill_1`, `skill_2`, `tier`) VALUES (7,'2026-08-27 07:04:54.886915',NULL,'2026-09-09 07:07:43.335095','구르미','SKY',11,'public/gym-leader-animal/f29454fa-ca32-497a-a9ce-016788177cb2.png',1,'SKY_FEATHER_GUARD','SKY_FLOATING_STEP','B');
INSERT INTO `gym_leader_animals` (`id`, `created_at`, `deleted_at`, `updated_at`, `animal_name`, `card_type`, `gym_leader_id`, `image_key`, `order_no`, `skill_1`, `skill_2`, `tier`) VALUES (8,'2026-08-27 07:04:54.886915',NULL,'2026-09-09 07:07:53.206576','하늬','SKY',11,'public/gym-leader-animal/51a64e64-09c0-4db3-8511-83f93431f547.png',2,'SKY_CLOUD_CUSHION','SKY_TAILWIND','B');
INSERT INTO `gym_leader_animals` (`id`, `created_at`, `deleted_at`, `updated_at`, `animal_name`, `card_type`, `gym_leader_id`, `image_key`, `order_no`, `skill_1`, `skill_2`, `tier`) VALUES (9,'2026-08-27 07:04:54.886915',NULL,'2026-08-31 03:29:31.147544','여울','SEA',11,'public/gym-leader-animal/e72256bc-9731-4c3d-ab7a-bc2c0afe6b1f.png',3,'SEA_KELP_WRAP','SEA_TIDAL_BOOST','A');
INSERT INTO `gym_leader_animals` (`id`, `created_at`, `deleted_at`, `updated_at`, `animal_name`, `card_type`, `gym_leader_id`, `image_key`, `order_no`, `skill_1`, `skill_2`, `tier`) VALUES (10,'2026-08-27 07:04:54.886915',NULL,'2026-08-31 03:30:18.477850','별콩','SPACE',12,'public/gym-leader-animal/1478b477-9436-4a67-9254-83d0b2341a34.png',1,'SPACE_MOON_GUARD','SPACE_ORBIT_STEP','B');
INSERT INTO `gym_leader_animals` (`id`, `created_at`, `deleted_at`, `updated_at`, `animal_name`, `card_type`, `gym_leader_id`, `image_key`, `order_no`, `skill_1`, `skill_2`, `tier`) VALUES (11,'2026-08-27 07:04:54.886915',NULL,'2026-08-31 03:30:24.555954','코스미','SPACE',12,'public/gym-leader-animal/34d25822-f8f8-46b9-ad9b-39973036604c.png',2,'SPACE_ASTRO_SHIELD','SPACE_AURORA_WAVE','A');
INSERT INTO `gym_leader_animals` (`id`, `created_at`, `deleted_at`, `updated_at`, `animal_name`, `card_type`, `gym_leader_id`, `image_key`, `order_no`, `skill_1`, `skill_2`, `tier`) VALUES (12,'2026-08-27 07:04:54.886915',NULL,'2026-09-04 08:49:51.598008','도리','GROUND',12,'public/gym-leader-animal/46b9db8e-8205-4f4a-9bc7-dd6d0601a9d4.png',3,'GROUND_VINE_PULL','GROUND_HARVEST_BOOST','A');
INSERT INTO `gym_leader_animals` (`id`, `created_at`, `deleted_at`, `updated_at`, `animal_name`, `card_type`, `gym_leader_id`, `image_key`, `order_no`, `skill_1`, `skill_2`, `tier`) VALUES (13,'2026-08-27 07:04:54.886915',NULL,'2026-09-04 08:53:10.425932','이끼','GROUND',13,'public/gym-leader-animal/7c145f1f-6cd7-4d08-9721-36aaed62f829.png',1,'GROUND_NATURE_CALL','GROUND_CLOVER_LUCK','A');
INSERT INTO `gym_leader_animals` (`id`, `created_at`, `deleted_at`, `updated_at`, `animal_name`, `card_type`, `gym_leader_id`, `image_key`, `order_no`, `skill_1`, `skill_2`, `tier`) VALUES (14,'2026-08-27 07:04:54.886915',NULL,'2026-09-04 09:03:02.055520','소리','SKY',13,'public/gym-leader-animal/c42ac52c-3b99-474e-ad26-c82202813f05.png',2,'SKY_CLEAR_MIND','SKY_WIND_CHIME','A');
INSERT INTO `gym_leader_animals` (`id`, `created_at`, `deleted_at`, `updated_at`, `animal_name`, `card_type`, `gym_leader_id`, `image_key`, `order_no`, `skill_1`, `skill_2`, `tier`) VALUES (15,'2026-08-27 07:04:54.886915',NULL,'2026-09-04 09:11:52.418166','성운','SPACE',13,'public/gym-leader-animal/67c1e768-17a3-4857-b558-175f1a5c5d75.png',3,'SPACE_PULSAR_BEAT','SPACE_NOVA_FLASH','S');
INSERT INTO `gym_leader_animals` (`id`, `created_at`, `deleted_at`, `updated_at`, `animal_name`, `card_type`, `gym_leader_id`, `image_key`, `order_no`, `skill_1`, `skill_2`, `tier`) VALUES (16,'2026-08-27 07:04:54.886915',NULL,'2026-09-04 10:18:42.103119','물비늘','SEA',14,'public/gym-leader-animal/bd486200-6456-4790-bc37-21b1e3d473e1.png',1,'SEA_MIST_BREATH','SEA_RIPPLE_STEP','A');
INSERT INTO `gym_leader_animals` (`id`, `created_at`, `deleted_at`, `updated_at`, `animal_name`, `card_type`, `gym_leader_id`, `image_key`, `order_no`, `skill_1`, `skill_2`, `tier`) VALUES (17,'2026-08-27 07:04:54.886915',NULL,'2026-09-04 10:18:24.069893','은하','SPACE',14,'public/gym-leader-animal/ab8a7cef-9b1f-4f09-8bc7-d7a065b01f89.png',2,'SPACE_GALAXY_SPARK','SPACE_STAR_SEED','S');
INSERT INTO `gym_leader_animals` (`id`, `created_at`, `deleted_at`, `updated_at`, `animal_name`, `card_type`, `gym_leader_id`, `image_key`, `order_no`, `skill_1`, `skill_2`, `tier`) VALUES (18,'2026-08-27 07:04:54.886915',NULL,'2026-09-04 10:18:50.105502','노을','SKY',14,'public/gym-leader-animal/00d7ddd3-a8ca-4c5f-89f3-b5372a2c4dea.png',3,'SKY_HALO_GLOW','SKY_CLOUD_BURST','S');
INSERT INTO `gym_leader_animals` (`id`, `created_at`, `deleted_at`, `updated_at`, `animal_name`, `card_type`, `gym_leader_id`, `image_key`, `order_no`, `skill_1`, `skill_2`, `tier`) VALUES (19,'2026-08-27 07:04:54.886915',NULL,'2026-09-09 07:09:17.168908','혜성','SPACE',15,'public/gym-leader-animal/c7b7bf4a-2406-4811-b2ab-3d5d86505447.png',1,'SPACE_COSMIC_DUST','SPACE_METEOR_TAIL','S');
INSERT INTO `gym_leader_animals` (`id`, `created_at`, `deleted_at`, `updated_at`, `animal_name`, `card_type`, `gym_leader_id`, `image_key`, `order_no`, `skill_1`, `skill_2`, `tier`) VALUES (20,'2026-08-27 07:04:54.886915',NULL,'2026-09-09 07:08:28.494924','심해','SEA',15,'public/gym-leader-animal/af134bab-aafd-48c9-85d4-9745bcc6f08c.png',2,'SEA_DEEP_BLUE','SEA_WHIRLPOOL','S');
INSERT INTO `gym_leader_animals` (`id`, `created_at`, `deleted_at`, `updated_at`, `animal_name`, `card_type`, `gym_leader_id`, `image_key`, `order_no`, `skill_1`, `skill_2`, `tier`) VALUES (21,'2026-08-27 07:04:54.886915',NULL,'2026-09-09 07:08:35.778023','대지','GROUND',15,'public/gym-leader-animal/ec337103-fcf4-48d9-968a-7a97e5107af5.png',3,'GROUND_ROOT_BIND','GROUND_TAIL_SEED','SS');
INSERT INTO `gym_leader_animals` (`id`, `created_at`, `deleted_at`, `updated_at`, `animal_name`, `card_type`, `gym_leader_id`, `image_key`, `order_no`, `skill_1`, `skill_2`, `tier`) VALUES (22,'2026-08-27 07:04:54.886915',NULL,'2026-09-09 07:09:47.103033','창공','SKY',16,'public/gym-leader-animal/0112c74a-790f-4623-94e4-93b777fad32c.png',1,'SKY_TWINKLE_EYE','SKY_UPDRAFT','S');
INSERT INTO `gym_leader_animals` (`id`, `created_at`, `deleted_at`, `updated_at`, `animal_name`, `card_type`, `gym_leader_id`, `image_key`, `order_no`, `skill_1`, `skill_2`, `tier`) VALUES (23,'2026-08-27 07:04:54.886915',NULL,'2026-09-09 07:09:53.528297','해류','SEA',16,'public/gym-leader-animal/b794c35f-1616-474d-9bcf-854154d87091.png',2,'SEA_MARINE_CALL','SEA_AQUA_FLASH','SS');
INSERT INTO `gym_leader_animals` (`id`, `created_at`, `deleted_at`, `updated_at`, `animal_name`, `card_type`, `gym_leader_id`, `image_key`, `order_no`, `skill_1`, `skill_2`, `tier`) VALUES (24,'2026-08-27 07:04:54.886915',NULL,'2026-09-09 07:09:59.729484','루메르','SPACE',16,'public/gym-leader-animal/a3c21632-ce92-474c-802c-b23326c1b73c.png',3,'SPACE_UNIVERSE_CALL','SPACE_DIMENSION_SKIP','SSS');
