package com.somagochi.pochakfarm.common.exception;

public enum ErrorCode {
  INVALID_TOKEN(401, "INVALID_TOKEN", "유효하지 않은 토큰입니다."),
  EXPIRED_TOKEN(401, "EXPIRED_TOKEN", "만료된 토큰입니다."),
  INVALID_TOKEN_TYPE(401, "INVALID_TOKEN_TYPE", "유효하지 않은 토큰 타입입니다."),
  BLACKLISTED_TOKEN(401, "BLACKLISTED_TOKEN", "사용할 수 없는 토큰입니다."),
  REVOKED_REFRESH_TOKEN(401, "REVOKED_REFRESH_TOKEN", "이미 폐기된 리프레시 토큰입니다."),
  UNSUPPORTED_SOCIAL_PROVIDER(400, "UNSUPPORTED_SOCIAL_PROVIDER", "지원하지 않는 소셜 로그인입니다."),
  INVALID_SOCIAL_TOKEN(401, "INVALID_SOCIAL_TOKEN", "유효하지 않은 소셜 토큰입니다."),
  SOCIAL_USER_INFO_FAILED(502, "SOCIAL_USER_INFO_FAILED", "소셜 사용자 정보를 가져오지 못했습니다."),
  APPLE_CLIENT_SECRET_FAILED(500, "APPLE_CLIENT_SECRET_FAILED", "애플 클라이언트 시크릿 생성에 실패했습니다."),
  EMAIL_NOT_FOUND(400, "EMAIL_NOT_FOUND", "이메일 정보를 찾을 수 없습니다."),
  USER_NOT_FOUND(404, "USER_NOT_FOUND", "사용자를 찾을 수 없습니다."),
  USER_ALREADY_REGISTERED(409, "USER_ALREADY_REGISTERED", "이미 가입된 사용자입니다."),
  INVALID_NICKNAME(400, "INVALID_NICKNAME", "사용할 수 없는 닉네임입니다."),
  DUPLICATE_NICKNAME(409, "DUPLICATE_NICKNAME", "이미 사용 중인 닉네임입니다."),
  TOKEN_OWNER_MISMATCH(401, "TOKEN_OWNER_MISMATCH", "토큰 소유자가 일치하지 않습니다."),
  UNSUPPORTED_CONTENT_TYPE(400, "UNSUPPORTED_CONTENT_TYPE", "지원하지 않는 파일 형식입니다."),
  INVALID_UPLOAD_PURPOSE(400, "INVALID_UPLOAD_PURPOSE", "유효하지 않은 업로드 용도입니다."),
  EMPTY_FILE(400, "EMPTY_FILE", "파일이 비어 있습니다."),
  FILE_NOT_FOUND(404, "FILE_NOT_FOUND", "파일을 찾을 수 없습니다."),
  FILE_TOO_LARGE(413, "FILE_TOO_LARGE", "파일 용량이 너무 큽니다."),
  FORBIDDEN_FILE_ACCESS(403, "FORBIDDEN_FILE_ACCESS", "파일에 접근할 권한이 없습니다."),
  INVALID_ANIMAL_NAME(400, "INVALID_ANIMAL_NAME", "사용할 수 없는 동물 이름입니다."),
  CHARACTERIZATION_NOT_FOUND(404, "CHARACTERIZATION_NOT_FOUND", "캐릭터라이징 결과를 찾을 수 없습니다."),
  UNSUPPORTED_CHARACTERIZATION_IMAGE(
      422, "UNSUPPORTED_CHARACTERIZATION_IMAGE", "캐릭터라이징할 수 없는 이미지입니다."),
  CHARACTERIZATION_FAILED(502, "CHARACTERIZATION_FAILED", "캐릭터라이징에 실패했습니다."),
  CHARACTERIZATION_ALREADY_USED(409, "CHARACTERIZATION_ALREADY_USED", "이미 사용된 캐릭터라이징입니다."),
  CHARACTERIZATION_ALREADY_PROCESSING(
      409, "CHARACTERIZATION_ALREADY_PROCESSING", "이미 진행 중인 캐릭터라이징입니다."),
  CHARACTERIZATION_BUSY(503, "CHARACTERIZATION_BUSY", "캐릭터라이징 요청이 많아 잠시 후 다시 시도해 주세요."),
  CHARACTERIZATION_TIMED_OUT(504, "CHARACTERIZATION_TIMED_OUT", "캐릭터라이징 처리 시간이 초과되었습니다."),
  INVALID_CLIENT_REQUEST_ID(400, "INVALID_CLIENT_REQUEST_ID", "유효하지 않은 요청 ID입니다."),
  INSUFFICIENT_COINS(402, "INSUFFICIENT_COINS", "코인이 부족합니다."),
  CAPTURE_ATTEMPT_REQUIRED(409, "CAPTURE_ATTEMPT_REQUIRED", "포착 기회가 필요합니다."),
  CAPTURE_ATTEMPT_ALREADY_AVAILABLE(
      409, "CAPTURE_ATTEMPT_ALREADY_AVAILABLE", "이미 사용 가능한 포착 기회가 있습니다."),
  CAPTURE_REQUEST_CONFLICT(409, "CAPTURE_REQUEST_CONFLICT", "포착 요청이 충돌했습니다."),
  CAPTURE_NOT_FOUND(404, "CAPTURE_NOT_FOUND", "포착 정보를 찾을 수 없습니다."),
  FORBIDDEN_CAPTURE_ACCESS(403, "FORBIDDEN_CAPTURE_ACCESS", "포착 정보에 접근할 권한이 없습니다."),
  CAPTURE_NOT_PLACEABLE(409, "CAPTURE_NOT_PLACEABLE", "농장에 배치할 수 없는 포착입니다."),
  CAPTURE_ALREADY_PLACED(409, "CAPTURE_ALREADY_PLACED", "이미 농장에 배치된 포착입니다."),
  CAPTURE_PLACEMENT_CONFLICT(409, "CAPTURE_PLACEMENT_CONFLICT", "포착 배치 요청이 충돌했습니다."),
  INVALID_GAME_RESULT(400, "INVALID_GAME_RESULT", "유효하지 않은 게임 결과입니다."),
  DEVICE_NOT_FOUND(404, "DEVICE_NOT_FOUND", "기기 정보를 찾을 수 없습니다."),
  INVALID_PHONE_NUMBER(400, "INVALID_PHONE_NUMBER", "유효하지 않은 휴대폰 번호입니다."),
  INVALID_CHARACTERIZATION_ID(400, "INVALID_CHARACTERIZATION_ID", "유효하지 않은 캐릭터라이징 ID입니다."),
  REQUIRED_CONSENT_REQUIRED(400, "REQUIRED_CONSENT_REQUIRED", "필수 약관에 동의해야 합니다."),
  PHONE_NUMBER_ALREADY_REGISTERED(409, "PHONE_NUMBER_ALREADY_REGISTERED", "이미 등록된 휴대폰 번호입니다."),
  DEVICE_ALREADY_REGISTERED(409, "DEVICE_ALREADY_REGISTERED", "이미 등록된 기기입니다."),
  PRE_REGISTRATION_NOT_FOUND(404, "PRE_REGISTRATION_NOT_FOUND", "사전 등록 정보를 찾을 수 없습니다."),
  INVALID_PARAMETER(400, "INVALID_PARAMETER", "요청 값이 올바르지 않습니다."),
  FARM_SPACE_NOT_FOUND(404, "FARM_SPACE_NOT_FOUND", "농장 공간을 찾을 수 없습니다."),
  ANIMAL_NOT_FOUND(404, "ANIMAL_NOT_FOUND", "동물을 찾을 수 없습니다."),
  FORBIDDEN_ANIMAL_ACCESS(403, "FORBIDDEN_ANIMAL_ACCESS", "동물에 접근할 권한이 없습니다."),
  FARM_SLOT_NOT_FOUND(404, "FARM_SLOT_NOT_FOUND", "농장 슬롯을 찾을 수 없습니다."),
  FARM_SLOT_OCCUPIED(409, "FARM_SLOT_OCCUPIED", "이미 사용 중인 농장 슬롯입니다."),
  ANIMAL_REPLACEMENT_CONFLICT(409, "ANIMAL_REPLACEMENT_CONFLICT", "동물 교체 대상이 충돌했습니다."),
  ANIMAL_NOT_PLACED(409, "ANIMAL_NOT_PLACED", "농장에 배치되지 않은 동물입니다."),
  FARM_FLOOR_MAX_REACHED(409, "FARM_FLOOR_MAX_REACHED", "농장 층이 이미 최대치입니다."),
  CONCURRENCY_CONFLICT(409, "CONCURRENCY_CONFLICT", "동시에 처리된 요청이 있습니다. 잠시 후 다시 시도해 주세요."),
  FORBIDDEN_FARM_SLOT_ACCESS(403, "FORBIDDEN_FARM_SLOT_ACCESS", "농장 슬롯에 접근할 권한이 없습니다."),
  FARM_SLOT_TYPE_MISMATCH(400, "FARM_SLOT_TYPE_MISMATCH", "농장 슬롯 타입이 일치하지 않습니다."),
  FARM_SPACE_FULL(419, "FARM_SPACE_FULL", "농장 공간이 가득 찼습니다."),
  ACHIEVEMENT_NOT_FOUND(404, "ACHIEVEMENT_NOT_FOUND", "업적을 찾을 수 없습니다."),
  ACHIEVEMENT_NOT_ACHIEVED(400, "ACHIEVEMENT_NOT_ACHIEVED", "아직 달성하지 않은 업적입니다."),
  ACHIEVEMENT_REWARD_ALREADY_CLAIMED(409, "ACHIEVEMENT_REWARD_ALREADY_CLAIMED", "이미 수령한 업적 보상입니다."),
  BADGE_NOT_FOUND(404, "BADGE_NOT_FOUND", "배지를 찾을 수 없습니다."),
  COUPON_NOT_FOUND(404, "COUPON_NOT_FOUND", "쿠폰을 찾을 수 없습니다."),
  COUPON_EXPIRED(400, "COUPON_EXPIRED", "만료된 쿠폰입니다."),
  COUPON_ALREADY_USED(409, "COUPON_ALREADY_USED", "이미 사용된 쿠폰입니다."),
  COUPON_ALREADY_REDEEMED(409, "COUPON_ALREADY_REDEEMED", "이미 쿠폰을 교환한 사용자입니다."),
  COUPON_REDEEM_NOT_STARTED(409, "COUPON_REDEEM_NOT_STARTED", "아직 쿠폰 교환이 시작되지 않았습니다."),
  FORBIDDEN_COUPON_ACCESS(403, "FORBIDDEN_COUPON_ACCESS", "쿠폰에 접근할 권한이 없습니다."),
  FORBIDDEN_ADMIN_ACCESS(403, "FORBIDDEN_ADMIN_ACCESS", "관리자 권한이 없습니다."),
  BATTLE_NOT_FOUND(404, "BATTLE_NOT_FOUND", "배틀을 찾을 수 없습니다."),
  FORBIDDEN_BATTLE_ACCESS(403, "FORBIDDEN_BATTLE_ACCESS", "배틀에 접근할 권한이 없습니다."),
  BATTLE_ALREADY_IN_PROGRESS(409, "BATTLE_ALREADY_IN_PROGRESS", "이미 진행 중인 배틀이 있습니다."),
  BATTLE_NOT_IN_PROGRESS(409, "BATTLE_NOT_IN_PROGRESS", "진행 중인 배틀이 아닙니다."),
  BATTLE_ANIMAL_RESTING(409, "BATTLE_ANIMAL_RESTING", "휴식 중인 동물입니다."),
  INVALID_BATTLE_ENTRY(400, "INVALID_BATTLE_ENTRY", "유효하지 않은 배틀 참가 정보입니다."),
  BATTLE_ACTION_SEQUENCE_MISMATCH(409, "BATTLE_ACTION_SEQUENCE_MISMATCH", "배틀 행동 순서가 일치하지 않습니다."),
  BATTLE_ACTION_CONFLICT(409, "BATTLE_ACTION_CONFLICT", "배틀 행동 요청이 충돌했습니다."),
  BATTLE_FINAL_ROUND_EXPIRED(409, "BATTLE_FINAL_ROUND_EXPIRED", "최종 승부 제한 시간이 지났습니다."),
  BATTLE_FINAL_ROUND_NOT_READY(409, "BATTLE_FINAL_ROUND_NOT_READY", "아직 최종 승부를 진행할 수 없습니다."),
  BATTLE_FINAL_ROUND_NOT_STARTED(409, "BATTLE_FINAL_ROUND_NOT_STARTED", "최종 승부가 시작되지 않았습니다."),
  BATTLE_ACTION_SELECTION_CLOSED(409, "BATTLE_ACTION_SELECTION_CLOSED", "배틀 행동 선택이 마감되었습니다."),
  GYM_LEADER_NOT_FOUND(404, "GYM_LEADER_NOT_FOUND", "관장을 찾을 수 없습니다."),
  GYM_LEADER_LOCKED(403, "GYM_LEADER_LOCKED", "아직 잠겨 있는 관장입니다."),
  ;

  private final int status;
  private final String code;
  private final String message;

  ErrorCode(int status, String code, String message) {
    this.status = status;
    this.code = code;
    this.message = message;
  }

  public int getStatus() {
    return status;
  }

  public String getCode() {
    return code;
  }

  public String getMessage() {
    return message;
  }
}
